CLUB_MAPPING_2026 = {
    # --- Previously mapped High-Impact ---
    "Daniel Olmo Carvajal": "Barcelona",
    "Florian Wirtz": "Liverpool",
    "Jamal Musiala": "Bayern Munich",
    "Kylian Mbappé Lottin": "Real Madrid",
    "Xavi Simons": "Tottenham Hotspur",
    "William Saliba": "Arsenal",
    "Harry Kane": "Bayern Munich",
    "Joshua Kimmich": "Bayern Munich",
    "Nico Schlotterbeck": "Borussia Dortmund",
    "Maximilian Beier": "Borussia Dortmund",
    "Deniz Undav": "VfB Stuttgart",
    "Chris Führich": "VfB Stuttgart",
    "Alejandro Grimaldo García": "Bayer Leverkusen",
    "Enzo Millot": "VfB Stuttgart",
    "Angelo Stiller": "VfB Stuttgart",
    "Jonathan Tah": "Bayern Munich",
    "Alphonso Davies": "Bayern Munich",
    "Leroy Sané": "Galatasaray",
    "Niclas Füllkrug": "AC Milan",
    "Kevin Vogt": "Union Berlin",
    "Finn Ole Becker": "Hoffenheim",
    "Robert Skov": "Hoffenheim",

    # --- New Group: Ligue 1 & European Veterans ---
    "Darlin Zidane Yongwa Ngameni": "Lorient",
    "Falaye Sacko": "Montpellier",
    "Mateusz Wieteska": "Cagliari",
    "Aaron Ramsey": "Cardiff City",
    "Samuel Moutoussamy": "Nantes",
    "Moses Daddy-Ajala Simon": "Nantes",
    "Jonathan Clauss": "Nice",
    "Kamaldeen Sulemana": "Southampton",
    "Ángel Fabián Di María Hernández": "Benfica",
    "Nicolas Pépé": "Villarreal",
    "Alidu Seidu": "Rennes",
    "Noussair Mazraoui": "Manchester United",
    "Maximilian Wöber": "Leeds United",
    "Jonathan Bamba": "Al Duhail",
    "Yusuf Yazıcı": "Olympiacos",
    "Deiver Andrés Machado Mena": "Lens",
    "Matěj Kovář": "Bayer Leverkusen",
    "Idrissa Gana Gueye": "Everton",
    "Aïssa Bilal Laïdouni": "Union Berlin",
    "Folarin Balogun": "Monaco",
    "Matúš Bero": "Bochum",
    "Robin Koch": "Eintracht Frankfurt",
    "Carlos Soler Barragán": "West Ham United",
    "Leandro Daniel Paredes": "Roma",
    "Ellyes Joris Skhiri": "Eintracht Frankfurt",
    "Odilon Kossonou": "Bayer Leverkusen",
    "Nico Elvedi": "Borussia Mönchengladbach",
    "Lassine Sinayoko": "Auxerre",
    "Youssouf Fofana": "AC Milan",
    "Patrik Schick": "Bayer Leverkusen",
    "Milos Veljkovic": "Werder Bremen",
    "Florian Kainz": "Köln",
    "Habibou Mouhamadou Diallo": "Al Shabab",
    "Lucas Tolentino Coelho de Lima": "Lyon", # Lucas Paqueta
    "Mehmet Zeki Çelik": "Roma",
    "David Jurásek": "Hoffenheim",
    "Arthur Theate": "Eintracht Frankfurt",
    "Florian Grillitsch": "Hoffenheim",
    "Boubacar Traore": "Wolverhampton Wanderers",
    "Pape Matar Sarr": "Tottenham Hotspur",
    "András Schäfer": "Union Berlin",
    "Rafael Santos Borré Amaury": "Internacional",
    "Alexander Djiku": "Fenerbahce",
    "Emre Can": "Borussia Dortmund",
    "Nabil Bentaleb": "Lille",
    "Philipp Mwene": "Mainz",
    "Flavius Daniliuc": "Verona",
    "Mohamed Camara": "Al Sadd",
    "Junya Ito": "Reims",
    "Adam Hložek": "Hoffenheim",
    "Jordan Veretout": "Lyon",
    "Bruno Guimarães Rodriguez Moura": "Newcastle United",
    "Christopher Wooh": "Rennes",
    "Youcef Atal": "Al Sadd",
    "Yan Valery": "Sheffield Wednesday",
    "Brenden Aaronson": "Leeds United",
    "Mattéo Guendouzi Olié": "Lazio",
    "Hamari Traoré": "Real Sociedad",
    "Mohamed Bayo": "Lille",
    "Nicolas Seiwald": "RB Leipzig",
    "Ismaël Chester Diallo": "Hajduk Split",
    "Gideon Mensah": "Auxerre",
    "Dylan Daniel Mahmoud Bronn": "Salernitana",
    "Przemysław Frankowski": "Lens",
    "Dejan Lovren": "PAOK",
    "Enzo Gianni Tchato Mbiayi": "Montpellier",
    "Georginio Wijnaldum": "Al Ettifaq",
    "Jackson Gabriel Porozo Vernaza": "Leganés",
    "Issa Kabore": "Benfica",
    "Guillermo Alfonso Maripán Loaysa": "Torino",
    "Yunis Abdelhamid": "Saint-Étienne",
    "Ivo Grbić": "Sheffield United",
    "Terem Igobor Moffi": "Nice",
    "Joakim Mæhle": "Wolfsburg",
    "Joseph Scally": "Borussia Mönchengladbach",
    "Zakaria Aboukhlal": "Toulouse",
    "Chancel Mbemba Mangulu": "Marseille",
    "Abdou Diallo": "Al Arabi",
    "Islam Slimani": "Belouizdad",
    "Seko Fofana": "Al Ettifaq",
    "Kasper Dolberg": "Anderlecht",
    "Pape Gueye": "Villarreal",
    "Achraf Dari": "Al Ahly",
    "Axel Disasi": "Chelsea",
    "Mohamed Youcef Belaïli": "ES Tunis",
    "Karl Brillant Toko Ekambi": "Al Ettifaq",
    "Pablo Sarabia García": "Wolverhampton Wanderers",
    "Dango Aboubacar Faissal Ouattara": "Bournemouth",
    "Frederik Rønnow": "Union Berlin",
    "Cédric Zesiger": "Wolfsburg",
    "Koen Casteels": "Al Qadsiah",
    "Josip Juranović": "Union Berlin",
    "Julian Jeanvier": "Kayserispor",
    "Philipp Lienhart": "Freiburg",
    "Silvan Widmer": "Mainz",
    "Andrej Kramarić": "Hoffenheim",
    "Ruben Vargas": "Augsburg",
    "Montassar Omar Talbi": "Lorient",
    "Timothy Weah": "Juventus",
    "Joe Rodon": "Leeds United",
    "Miha Blažič": "Lech Poznań",
    "Alexis Alejandro Sánchez Sánchez": "Udinese",
    "Sofiane Boufal": "Al Rayyan",
    "Gedeon Kalulu Kyatengwa": "Lorient",
    "Moussa Diarra": "Toulouse",
    "Osman Bukari": "Austin FC",
    "Yasser Larouci": "Watford",
    "Logan Costa": "Villarreal",
    "Wout Faes": "Leicester City",
    "Alfred Benjamin Gomis": "Palermo",
    "Brice Samba": "Lens",
    "Mory Diaw": "Clermont",
    "Dimitry Bertaud": "Montpellier",
    "Oumar Gonzalez": "Al Ittihad",
    "Gaël Kakuta": "Amiens",
    "Salis Abdul Samed": "Sunderland",
    "Issiaga Sylla": "Montpellier",
    "Ismail Jakobs": "Galatasaray",
    "Matz Sels": "Nottingham Forest",
    "Arkadiusz Milik": "Juventus",
    "Ui-Jo Hwang": "Alanyaspor",
    "Roland Sallai": "Galatasaray",
    "Kamory Doumbia": "Reims",
    "Yvon Landry Mvogo": "Lorient",
    "Boubakar Kouyate": "Montpellier",
    "Azzedine Ounahi": "Panathinaikos",
    "Vincent Sierro": "Toulouse",
    "Gabriel Alonso Suazo Urbina": "Toulouse",
    "Predrag Rajković": "Al Ittihad",
    "Aster Vranckx": "Wolfsburg",
    "Keylor Navas Gamboa": "Al Qadsiah",
    "Houssem Aouar": "Al Ittihad",
    "Harold Moukoudi": "AEK Athens",
    "Kasper Schmeichel": "Celtic",
    "Sikou Niakate": "Braga",
    "Breel-Donald Embolo": "Monaco",
    "Abdallah Dipo Sima": "Brest",
    "Takumi Minamino": "Monaco",
    "Mostafa Mohamed Ahmed Abdallah": "Nantes",
    "Veljko Birmančević": "Sparta Prague",
    "Christoph Baumgartner": "RB Leipzig",
    "Salih Özcan": "Wolfsburg",
    "Ike Ugbo": "Troyes",
    "Jean-Charles Castelletto": "Nantes",
    "Patrick Wimmer": "Wolfsburg",
    "Jean-Philippe Krasso": "Paris FC",
    "Cédric Bakambu": "Betis",
    "Amine Harit": "Marseille",
    "Silas Katompa Mvumpa": "Red Star Belgrade",
    "Yussuf Yurary Poulsen": "RB Leipzig",
    "Michael Gregoritsch": "Freiburg",
    "Kevin Danso": "Lens",
    "Xherdan Shaqiri": "Basel",
    "Cheikh Ahmadou Bamba Mbacke Dieng": "Angers",
    "Ruslan Malinovskiy": "Genoa",
    # --- Premier League Moves ---
    "Benjamin Šeško": "Manchester United",
    "Granit Xhaka": "Bayer Leverkusen",
    "Gianluigi Donnarumma": "Manchester City",
    "Amadou Onana": "Aston Villa",
    "Ian Maatsen": "Aston Villa",
    "Amine Adli": "Bournemouth",
    "Reinildo Isnard Mandava": "Sunderland",
    "Jeremy Doku": "Manchester City",
    "Matthijs de Ligt": "Manchester United",
    "Nayef Aguerd": "Real Sociedad", # Currently on loan/moved to La Liga

    # --- Bundesliga Core ---
    "Oliver Baumann": "Hoffenheim",
    "Willi Orban": "RB Leipzig",
    "Romano Schmid": "Werder Bremen",
    "Jonas Older Wind": "Wolfsburg",
    "Konrad Laimer": "Bayern Munich",
    "Omar Marmoush": "Eintracht Frankfurt",
    "Marcel Sabitzer": "Borussia Dortmund",
    "Leonidas Stergiou": "VfB Stuttgart",
    "David Raum": "RB Leipzig",
    "Waldemar Anton": "Borussia Dortmund",
    "Ikoma Loïs Openda": "Juventus", # Moved to Serie A (on loan/perm)
    "Thomas Müller": "Bayern Munich",
    "Fares Chaïbi": "Eintracht Frankfurt",
    "Benjamin Henrichs": "RB Leipzig",
    "Jeremie Frimpong": "Bayer Leverkusen",
    "Josip Stanišić": "Bayern Munich",
    "Piero Martín Hincapié Reyna": "Bayer Leverkusen",
    "Robert Andrich": "Bayer Leverkusen",
    "Edmond Fayçal Tapsoba": "Bayer Leverkusen",
    "Maximilian Mittelstädt": "VfB Stuttgart",
    "Dayotchanculle Upamecano": "Bayern Munich",
    "Manuel Neuer": "Bayern Munich",
    "Gregor Kobel": "Borussia Dortmund",

    # --- Ligue 1 & PSG Core ---
    "Hichem Boudaoui": "Nice",
    "Nicolás Alejandro Tagliafico": "Lyon",
    "Achraf Hakimi Mouh": "Paris Saint-Germain",
    "Vitor Machado Ferreira": "Paris Saint-Germain", # Vitinha
    "Fabián Ruiz Peña": "Paris Saint-Germain",
    "Nuno Mendes": "Paris Saint-Germain",
    "Willian Joel Pacho Tenorio": "Paris Saint-Germain",
    "Marcos Aoás Corrêa": "Paris Saint-Germain", # Marquinhos
    "Warren Zaire Emery": "Paris Saint-Germain",
    "Bradley Barcola": "Paris Saint-Germain",
    "Randal Kolo Muani": "Paris Saint-Germain",
    "Danilo Luís Hélio Pereira": "Al Ittihad", # Moved to Saudi
    "Jonathan David": "Lille",

    # --- Other Global Stars ---
    "Lionel Andrés Messi Cuccittini": "Inter Miami",
    "Neymar da Silva Santos Junior": "Al Hilal",
    "Wout Weghorst": "Ajax",
    "Aurélien Djani Tchouaméni": "Real Madrid",
    "Lovro Majer": "Wolfsburg",
    "Exequiel Alejandro Palacios": "Bayer Leverkusen",
    "Serhou Guirassy": "Borussia Dortmund",

    "Luka Modrić": "AC Milan",
    "Federico Santiago Valverde Dipetta": "Real Madrid",
    "João Félix Sequeira": "Chelsea",
    "Jude Bellingham": "Real Madrid",
    "Bruno Miguel Borges Fernandes": "Manchester United",
    "Lamine Yamal Nasraoui Ebana": "Barcelona",
    "Christian Pulisic": "AC Milan",
    "Luis Gerardo Chávez Magallón": "Dynamo Moscow",
    "Ousmane Dembélé": "Paris Saint-Germain",
    "Arda Güler": "Real Madrid",
    "James David Rodríguez Rubio": "Minnesota United",
    "Adrien Rabiot": "AC Milan",
    "Philip Foden": "Manchester City",
    "Ivan Perišić": "PSV",
    "Cody Mathès Gakpo": "Liverpool",
    "Rodrigo Javier De Paul": "Atlético Madrid",
    "Antoine Griezmann": "Atlético Madrid",
    "Bukayo Saka": "Arsenal",
    "Jhon Adolfo Arias Andrade": "Fluminense",
    "Declan Rice": "Arsenal",
    "Rodrygo Silva de Goes": "Real Madrid",
    "Kevin De Bruyne": "Manchester City",
    "Maximiliano Javier Araújo Vilches": "Sporting CP",
    "Dan Ndoye": "Nottingham Forest",
    "Alexis Mac Allister": "Liverpool",
    "Theo Bernard François Hernández": "AC Milan",
    "Richard Rios Montoya": "Palmeiras",
    "Raphael Dias Belloli": "Barcelona",
    "Enzo Fernandez": "Chelsea",
    "Jefferson Andrés Lerma Solís": "Crystal Palace",
    "Kai Havertz": "Arsenal",
    "Hakim Ziyech": "Galatasaray",
    "Romelu Lukaku Menama": "Napoli",
    "Olivier Giroud": "Los Angeles FC",
    "Memphis Depay": "Corinthians",
    "Lautaro Javier Martínez": "Inter Milan",
    "Cristiano Ronaldo dos Santos Aveiro": "Al Nassr",
    "Darwin Gabriel Núñez Ribeiro": "Al Hilal",
    "Ademola Lookman": "Atlético Madrid",
    "Franck Yannick Kessié": "Al Ahli",
    "Virgil van Dijk": "Liverpool",
    "Yoane Wissa": "Brentford",
    "Luis Fernando Díaz Marulanda": "Liverpool",
    "Mislav Oršić": "Trabzonspor",
    "Mohammed Kudus": "West Ham United",
    "Jhon Andrés Córdoba Copete": "Krasnodar",
    "Julián Álvarez": "Atlético Madrid",
    "Álvaro Borja Morata Martín": "AC Milan",
    "Ismaïla Sarr": "Crystal Palace",
    "Teboho Mokoena": "Mamelodi Sundowns",
    "Simon Adingra": "Brighton & Hove Albion",
    "Aubrey Maphosa Modiba": "Mamelodi Sundowns",
    "Aleksandar Mitrović": "Al Rayyan",
    "Nikola Vlašić": "Torino",
    "Alex Iwobi": "Fulham",
    "Marcus Rashford": "Manchester United",
    "Théo Bongonda Mbul''Ofeko Batombo": "Spartak Moscow",
    "Cristóvão Paciência Mabululo": "Ittihad Alexandria",
    "Victor James Osimhen": "Galatasaray",
    "Evidence Makgopa": "Orlando Pirates",
    "Youssef En-Nesyri": "Fenerbahçe",
    "Marco Verratti": "Al-Arabi Qatar"
}