"""
2026 World Cup predicted rosters (as of February 15, 2026).
Sources: Public football databases, transfer news.

Key notes:
  - Mikel Merino (Spain/Arsenal): Injury doubt - foot surgery Feb 9, 2026
  - Christian Pulisic (USA/AC Milan): Career-best season
  - Luka Modrić (Croatia/AC Milan): Final season, contract expires June 2026
  - Lucas Paquetá (Brazil/Flamengo): Moved from West Ham on Jan 30, 2026
"""

rosters_2026 = {
    'Spain': {
        'Unai Simón': 'Athletic Club',
        'David Raya': 'Arsenal',
        'Dani Carvajal': 'Real Madrid',
        'Aymeric Laporte': 'Al-Nassr',
        'Robin Le Normand': 'Atlético Madrid',
        'Dani Vivian': 'Athletic Club',
        'Marc Cucurella': 'Chelsea',
        'Alejandro Grimaldo': 'Bayer Leverkusen',
        'Rodri': 'Manchester City',
        'Fabián Ruiz': 'Paris Saint-Germain',
        'Pedri': 'Barcelona',
        'Gavi': 'Barcelona',
        'Dani Olmo': 'Barcelona',
        'Mikel Merino': 'Arsenal',  # INJURY DOUBT - foot surgery Feb 9
        'Martín Zubimendi': 'Real Sociedad',
        'Álvaro Morata': 'AC Milan',
        'Nico Williams': 'Athletic Club',
        'Lamine Yamal': 'Barcelona',
        'Ferran Torres': 'Barcelona',
        'Mikel Oyarzabal': 'Real Sociedad',
        'Joselu': 'Real Madrid',
        'Ayoze Pérez': 'Real Betis',
        'Bryan Gil': 'Sevilla',
    },
    
    'Argentina': {
        'Emiliano Martínez': 'Aston Villa',
        'Cristian Romero': 'Tottenham Hotspur',
        'Lisandro Martínez': 'Manchester United',
        'Nicolás Otamendi': 'Benfica',
        'Gonzalo Montiel': 'Sevilla',
        'Nahuel Molina': 'Atlético Madrid',
        'Marcos Acuña': 'Sevilla',
        'Nicolás Tagliafico': 'Lyon',
        'Rodrigo De Paul': 'Atlético Madrid',
        'Leandro Paredes': 'Roma',
        'Alexis Mac Allister': 'Liverpool',
        'Enzo Fernández': 'Chelsea',
        'Giovani Lo Celso': 'Tottenham Hotspur',
        'Exequiel Palacios': 'Bayer Leverkusen',
        'Lionel Messi': 'Inter Miami',
        'Julián Álvarez': 'Atlético Madrid',
        'Lautaro Martínez': 'Inter Milan',
        'Nicolás González': 'Fiorentina',
        'Paulo Dybala': 'Roma',
        'Alejandro Garnacho': 'Manchester United',
        'Thiago Almada': 'Botafogo',
        'Valentín Carboni': 'Monza',
    },
    
    'England': {
        'Jordan Pickford': 'Everton',
        'Aaron Ramsdale': 'Arsenal',
        'Kyle Walker': 'Manchester City',
        'John Stones': 'Manchester City',
        'Harry Maguire': 'Manchester United',
        'Marc Guéhi': 'Crystal Palace',
        'Luke Shaw': 'Manchester United',
        'Kieran Trippier': 'Newcastle United',
        'Declan Rice': 'Arsenal',
        'Jude Bellingham': 'Real Madrid',
        'Phil Foden': 'Manchester City',
        'Bukayo Saka': 'Arsenal',
        'James Maddison': 'Tottenham Hotspur',
        'Kalvin Phillips': 'Manchester City',
        'Conor Gallagher': 'Tottenham Hotspur',
        'Cole Palmer': 'Chelsea',
        'Harry Kane': 'Bayern Munich',
        'Marcus Rashford': 'Manchester United',
        'Raheem Sterling': 'Chelsea',
        'Ollie Watkins': 'Aston Villa',
        'Ivan Toney': 'Brentford',
        'Jarrod Bowen': 'West Ham United',
        'Jack Grealish': 'Manchester City',
    },
    
    'France': {
        'Mike Maignan': 'AC Milan',
        'Alphonse Areola': 'West Ham United',
        'Jules Koundé': 'Barcelona',
        'Dayot Upamecano': 'Bayern Munich',
        'Ibrahima Konaté': 'Liverpool',
        'William Saliba': 'Arsenal',
        'Theo Hernández': 'AC Milan',
        'Benjamin Pavard': 'Inter Milan',
        'Aurélien Tchouaméni': 'Real Madrid',
        'Eduardo Camavinga': 'Real Madrid',
        'N\'Golo Kanté': 'Al-Ittihad',
        'Adrien Rabiot': 'Marseille',
        'Antoine Griezmann': 'Atlético Madrid',
        'Ousmane Dembélé': 'Paris Saint-Germain',
        'Kylian Mbappé': 'Real Madrid',
        'Randal Kolo Muani': 'Paris Saint-Germain',
        'Marcus Thuram': 'Inter Milan',
        'Kingsley Coman': 'Bayern Munich',
        'Bradley Barcola': 'Paris Saint-Germain',
        'Christopher Nkunku': 'Chelsea',
        'Youssouf Fofana': 'AC Milan',
        'Warren Zaïre-Emery': 'Paris Saint-Germain',
    },
    
    'Germany': {
        'Marc-André ter Stegen': 'Barcelona',
        'Oliver Baumann': 'TSG Hoffenheim',
        'Antonio Rüdiger': 'Real Madrid',
        'Nico Schlotterbeck': 'Borussia Dortmund',
        'Jonathan Tah': 'Bayer Leverkusen',
        'David Raum': 'RB Leipzig',
        'Joshua Kimmich': 'Bayern Munich',
        'Jamal Musiala': 'Bayern Munich',
        'Florian Wirtz': 'Bayer Leverkusen',
        'Leon Goretzka': 'Bayern Munich',
        'Kai Havertz': 'Arsenal',
        'Leroy Sané': 'Bayern Munich',
        'Serge Gnabry': 'Bayern Munich',
        'Niclas Füllkrug': 'AC Milan',
        'Karim Adeyemi': 'Borussia Dortmund',
        'Pascal Groß': 'Borussia Dortmund',
        'Robert Andrich': 'Bayer Leverkusen',
        'Maximilian Mittelstädt': 'VfB Stuttgart',
        'Aleksandar Pavlović': 'Bayern Munich',
        'Chris Führich': 'VfB Stuttgart',
        'Emre Can': 'Borussia Dortmund',
        'Julian Brandt': 'Borussia Dortmund',
    },
    
    'Brazil': {
        'Alisson': 'Liverpool',
        'Ederson': 'Manchester City',
        'Danilo': 'Flamengo',
        'Marquinhos': 'Paris Saint-Germain',
        'Éder Militão': 'Real Madrid',
        'Gabriel Magalhães': 'Arsenal',
        'Alex Sandro': 'Flamengo',
        'Renan Lodi': 'Al-Hilal',
        'Casemiro': 'Manchester United',
        'Fabinho': 'Al-Ittihad',
        'Bruno Guimarães': 'Newcastle United',
        'Lucas Paquetá': 'Flamengo',  # Moved Jan 30, 2026
        'Neymar': 'Al-Hilal',
        'Vinícius Júnior': 'Real Madrid',
        'Rodrygo': 'Real Madrid',
        'Raphinha': 'Barcelona',
        'Antony': 'Manchester United',
        'Gabriel Jesus': 'Arsenal',
        'Richarlison': 'Tottenham Hotspur',
        'Gabriel Martinelli': 'Arsenal',
        'Pedro': 'Flamengo',
        'Endrick': 'Real Madrid',
        'Savinho': 'Manchester City',
    },
    
    'Netherlands': {
        'Bart Verbruggen': 'Brighton & Hove Albion',
        'Virgil van Dijk': 'Liverpool',
        'Matthijs de Ligt': 'Manchester United',
        'Nathan Aké': 'Manchester City',
        'Denzel Dumfries': 'Inter Milan',
        'Jeremie Frimpong': 'Bayer Leverkusen',
        'Frenkie de Jong': 'Barcelona',
        'Tijjani Reijnders': 'AC Milan',
        'Ryan Gravenberch': 'Liverpool',
        'Georginio Wijnaldum': 'Al-Ettifaq',
        'Xavi Simons': 'RB Leipzig',
        'Teun Koopmeiners': 'Juventus',
        'Memphis Depay': 'Corinthians',
        'Cody Gakpo': 'Liverpool',
        'Donyell Malen': 'Borussia Dortmund',
        'Steven Bergwijn': 'Al-Ittihad',
        'Wout Weghorst': 'Ajax',
        'Brian Brobbey': 'Ajax',
        'Joey Veerman': 'PSV Eindhoven',
        'Mats Wieffer': 'Brighton & Hove Albion',
        'Lutsharel Geertruida': 'RB Leipzig',
        'Jurriën Timber': 'Arsenal',
        'Ian Maatsen': 'Aston Villa',
    },
    
    'Portugal': {
        'Diogo Costa': 'Porto',
        'Rui Patrício': 'Atalanta',
        'Rúben Dias': 'Manchester City',
        'Gonçalo Inácio': 'Sporting CP',
        'Danilo Pereira': 'Paris Saint-Germain',
        'João Cancelo': 'Al-Hilal',
        'Nuno Mendes': 'Paris Saint-Germain',
        'João Palhinha': 'Bayern Munich',
        'Rúben Neves': 'Al-Hilal',
        'Bernardo Silva': 'Manchester City',
        'Bruno Fernandes': 'Manchester United',
        'Vitinha': 'Paris Saint-Germain',
        'João Félix': 'Chelsea',
        'Rafael Leão': 'AC Milan',
        'Cristiano Ronaldo': 'Al-Nassr',
        'Gonçalo Ramos': 'Paris Saint-Germain',
        'Diogo Jota': 'Liverpool',
        'Pedro Neto': 'Chelsea',
        'Otávio': 'Al-Nassr',
        'Matheus Nunes': 'Manchester City',
        'Francisco Conceição': 'Juventus',
        'João Neves': 'Paris Saint-Germain',
        'António Silva': 'Benfica',
    },
    
    'USA': {
        'Matt Turner': 'Crystal Palace',
        'Zack Steffen': 'Colorado Rapids',
        'Sergiño Dest': 'PSV Eindhoven',
        'Antonee Robinson': 'Fulham',
        'Chris Richards': 'Crystal Palace',
        'Cameron Carter-Vickers': 'Celtic',
        'Tim Ream': 'Charlotte FC',
        'Joe Scally': 'Borussia Mönchengladbach',
        'Tyler Adams': 'Bournemouth',
        'Weston McKennie': 'Juventus',
        'Yunus Musah': 'Atalanta',
        'Gio Reyna': 'Borussia Dortmund',
        'Luca de la Torre': 'Celta Vigo',
        'Malik Tillman': 'PSV Eindhoven',
        'Christian Pulisic': 'AC Milan',  
        'Timothy Weah': 'Juventus',
        'Folarin Balogun': 'Monaco',
        'Ricardo Pepi': 'PSV Eindhoven',
        'Haji Wright': 'Coventry City',
        'Josh Sargent': 'Norwich City',
        'Brenden Aaronson': 'Leeds United',
        'Johnny Cardoso': 'Real Betis',
        'Tanner Tessmann': 'Inter Milan',
    },
    
    'Croatia': {
        'Dominik Livaković': 'Fenerbahçe',
        'Joško Gvardiol': 'Manchester City',
        'Dejan Lovren': 'PAOK',
        'Domagoj Vida': 'AEK Athens',
        'Josip Juranović': 'Union Berlin',
        'Borna Sosa': 'Torino',
        'Luka Modrić': 'AC Milan',  # Moved July 2025, contract through June 2026
        'Mateo Kovačić': 'Manchester City',
        'Marcelo Brozović': 'Al-Nassr',
        'Mario Pašalić': 'Atalanta',
        'Luka Sučić': 'Red Bull Salzburg',
        'Lovro Majer': 'Wolfsburg',
        'Ivan Perišić': 'PSV Eindhoven',
        'Andrej Kramarić': 'TSG Hoffenheim',
        'Bruno Petković': 'Dinamo Zagreb',
        'Marko Pjaca': 'Dinamo Zagreb',
        'Nikola Vlašić': 'Torino',
        'Ante Budimir': 'Osasuna',
        'Mislav Oršić': 'Trabzonspor',
        'Josip Stanišić': 'Bayern Munich',
        'Martin Erlić': 'Sassuolo',
        'Joško Šutalo': 'Hellas Verona',
        'Kristijan Jakić': 'Augsburg',
    },
}