TOP_100 = TOP_100 = [
    {'nationality': 'France', 'player': 'Ousmane Dembélé', 'rank': 1, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Spain', 'player': 'Lamine Yamal Nasraoui Ebana', 'rank': 2, 'team': 'Barcelona'},
    {'nationality': 'Portugal', 'player': 'Vitor Machado Ferreira', 'rank': 3, 'team': 'Paris Saint-Germain'},
    {'nationality': 'France', 'player': 'Kylian Mbappé Lottin', 'rank': 4, 'team': 'Real Madrid'},
    {'nationality': 'Norway', 'player': 'Erling Haaland', 'rank': 5, 'team': 'Manchester City'},
    {'nationality': 'England', 'player': 'Harry Kane', 'rank': 6, 'team': 'Bayern Munich'},
    {'nationality': 'Morocco', 'player': 'Achraf Hakimi', 'rank': 7, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Brazil', 'player': 'Raphael Dias Belloli', 'rank': 8, 'team': 'Barcelona'},
    {'nationality': 'Egypt', 'player': 'Mohamed Salah', 'rank': 9, 'team': 'Liverpool'},
    {'nationality': 'Spain', 'player': 'Pedro González López', 'rank': 10, 'team': 'Barcelona'},
    {'nationality': 'Portugal', 'player': 'Nuno Mendes', 'rank': 11, 'team': 'Paris Saint-Germain'},
    {'nationality': 'England', 'player': 'Cole Palmer', 'rank': 12, 'team': 'Chelsea'},
    {'nationality': 'Italy', 'player': 'Gianluigi Donnarumma', 'rank': 13, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Georgia', 'player': 'Khvicha Kvaratskhelia', 'rank': 14, 'team': 'Napoli'},
    {'nationality': 'England', 'player': 'Declan Rice', 'rank': 15, 'team': 'Arsenal'},
    {'nationality': 'France', 'player': 'Désiré Doué', 'rank': 16, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Portugal', 'player': 'João Maria Lobo Alves Palhinha Gonçalves', 'rank': 17, 'team': 'Bayern Munich'},
    {'nationality': 'England', 'player': 'Jude Bellingham', 'rank': 18, 'team': 'Real Madrid'},
    {'nationality': 'Scotland', 'player': 'Scott McTominay', 'rank': 19, 'team': 'Napoli'},
    {'nationality': 'Argentina', 'player': 'Lautaro Javier Martínez', 'rank': 20, 'team': 'Inter Milan'},
    {'nationality': 'France', 'player': 'Michael Olise', 'rank': 21, 'team': 'Bayern Munich'},
    {'nationality': 'Brazil', 'player': 'Vinícius José Paixão de Oliveira Júnior', 'rank': 22, 'team': 'Real Madrid'},
    {'nationality': 'Netherlands', 'player': 'Virgil van Dijk', 'rank': 23, 'team': 'Liverpool'},
    {'nationality': 'Poland', 'player': 'Robert Lewandowski', 'rank': 24, 'team': 'Barcelona'},
    {'nationality': 'Argentina', 'player': 'Julián Álvarez', 'rank': 25, 'team': 'Atlético Madrid'},
    {'nationality': 'England', 'player': 'Bukayo Saka', 'rank': 26, 'team': 'Arsenal'},
    {'nationality': 'Spain', 'player': 'Fabián Ruiz Peña', 'rank': 27, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Sweden', 'player': 'Viktor Gyökeres', 'rank': 28, 'team': 'Sporting CP'},
    {'nationality': 'Uruguay', 'player': 'Darwin Gabriel Núñez Ribeiro', 'rank': 29, 'team': 'Liverpool'},
    {'nationality': 'Belgium', 'player': 'Thibaut Courtois', 'rank': 30, 'team': 'Real Madrid'},
    {'nationality': 'Colombia', 'player': 'Luis Díaz', 'rank': 31, 'team': 'Liverpool'},
    {'nationality': 'Ecuador', 'player': 'Moisés Isaac Caicedo Corozo', 'rank': 32, 'team': 'Chelsea'},
    {'nationality': 'France', 'player': 'William Saliba', 'rank': 33, 'team': 'Arsenal'},
    {'nationality': 'Argentina', 'player': 'Lionel Andrés Messi Cuccittini', 'rank': 34, 'team': 'Inter Miami'},
    {'nationality': 'Argentina', 'player': 'Alexis Mac Allister', 'rank': 35, 'team': 'Liverpool'},
    {'nationality': 'Germany', 'player': 'Florian Wirtz', 'rank': 36, 'team': 'Bayer Leverkusen'},
    {'nationality': 'Uruguay', 'player': 'Federico Santiago Valverde Dipetta', 'rank': 37, 'team': 'Real Madrid'},
    {'nationality': 'Hungary', 'player': 'Dominik Szoboszlai', 'rank': 38, 'team': 'Liverpool'},
    {'nationality': 'Guinea', 'player': 'Serhou Guirassy', 'rank': 39, 'team': 'Borussia Dortmund'},
    {'nationality': 'Netherlands', 'player': 'Denzel Dumfries', 'rank': 40, 'team': 'Inter Milan'},
    {'nationality': 'Netherlands', 'player': 'Ryan Isaac Gravenberch', 'rank': 41, 'team': 'Liverpool'},
    {'nationality': 'Brazil', 'player': 'Marquinhos', 'rank': 42, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Germany', 'player': 'Jamal Musiala', 'rank': 43, 'team': 'Bayern Munich'},
    {'nationality': 'Ecuador', 'player': 'Willian Pacho', 'rank': 44, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Norway', 'player': 'Martin Ødegaard', 'rank': 45, 'team': 'Arsenal'},
    {'nationality': 'Nigeria', 'player': 'Victor James Osimhen', 'rank': 46, 'team': 'Galatasaray'},
    {'nationality': 'Argentina', 'player': 'Enzo Fernandez', 'rank': 47, 'team': 'Chelsea'},
    {'nationality': 'Sweden', 'player': 'Alexander Isak', 'rank': 48, 'team': 'Newcastle United'},
    {'nationality': 'Brazil', 'player': 'Alisson Becker', 'rank': 49, 'team': 'Liverpool'},
    {'nationality': 'Germany', 'player': 'Joshua Kimmich', 'rank': 50, 'team': 'Bayern Munich'},
    {'nationality': 'Portugal', 'player': 'Cristiano Ronaldo dos Santos Aveiro', 'rank': 51, 'team': 'Al-Nassr'},
    {'nationality': 'Turkey', 'player': 'Hakan Çalhanoğlu', 'rank': 52, 'team': 'Inter Milan'},
    {'nationality': 'France', 'player': 'Bradley Barcola', 'rank': 53, 'team': 'Paris Saint-Germain'},
    {'nationality': 'Italy', 'player': 'Alessandro Bastoni', 'rank': 54, 'team': 'Inter Milan'},
    {'nationality': 'Portugal', 'player': 'Bruno Miguel Borges Fernandes', 'rank': 55, 'team': 'Manchester United'},
    {'nationality': 'England', 'player': 'Eberechi Eze', 'rank': 56, 'team': 'Crystal Palace'},
    {'nationality': 'Spain', 'player': 'Nico Williams', 'rank': 57, 'team': 'Athletic Bilbao'},
    {'nationality': 'Spain', 'player': 'David Raya Martin', 'rank': 58, 'team': 'Arsenal'},
    {'nationality': 'Brazil', 'player': 'Estêvão Willian Almeida de Oliveira Gonçalves', 'rank': 59, 'team': 'Palmeiras'},
    {'nationality': 'Netherlands', 'player': 'Frenkie de Jong', 'rank': 60, 'team': 'Barcelona'},
    {'nationality': 'England', 'player': 'Philip Foden', 'rank': 61, 'team': 'Manchester City'},
    {'nationality': 'Italy', 'player': 'Nicolò Barella', 'rank': 62, 'team': 'Inter Milan'},
    {'nationality': 'Spain', 'player': 'Marc Cucurella', 'rank': 63, 'team': 'Chelsea'},
    {'nationality': 'Switzerland', 'player': 'Yann Sommer', 'rank': 64, 'team': 'Inter Milan'},
    {'nationality': 'France', 'player': 'Marcus Thuram', 'rank': 65, 'team': 'Inter Milan'},
    {'nationality': 'Spain', 'player': 'Fermín López Marín', 'rank': 66, 'team': 'Barcelona'},
    {'nationality': 'France', 'player': 'Hugo Ekitike', 'rank': 67, 'team': 'Eintracht Frankfurt'},
    {'nationality': 'Spain', 'player': 'Pau Cubarsí Paredes', 'rank': 68, 'team': 'Barcelona'},
    {'nationality': 'Brazil', 'player': 'Bruno Guimarães Rodriguez Moura', 'rank': 69, 'team': 'Newcastle United'},
    {'nationality': 'Spain', 'player': 'Martín Zubimendi Ibáñez', 'rank': 70, 'team': 'Real Sociedad'},
    {'nationality': 'Spain', 'player': 'Rodrigo Hernández Cascante', 'rank': 71, 'team': 'Manchester City'},
    {'nationality': 'Turkey', 'player': 'Arda Güler', 'rank': 72, 'team': 'Real Madrid'},
    {'nationality': 'Belgium', 'player': 'Kevin De Bruyne', 'rank': 73, 'team': 'Manchester City'},
    {'nationality': 'Germany', 'player': 'İlkay Gündoğan', 'rank': 74, 'team': 'Manchester City'},
    {'nationality': 'Portugal', 'player': 'Bernardo Mota Veiga de Carvalho e Silva', 'rank': 75, 'team': 'Manchester City'},
    {'nationality': 'England', 'player': 'Trent Alexander-Arnold', 'rank': 76, 'team': 'Liverpool'},
    {'nationality': 'Netherlands', 'player': 'Micky van de Ven', 'rank': 77, 'team': 'Tottenham Hotspur'},
    {'nationality': 'Croatia', 'player': 'Joško Gvardiol', 'rank': 78, 'team': 'Manchester City'},
    {'nationality': 'France', 'player': 'Theo Bernard François Hernández', 'rank': 79, 'team': 'AC Milan'},
    {'nationality': 'Portugal', 'player': 'Rafael Leão', 'rank': 80, 'team': 'AC Milan'},
    {'nationality': 'South Korea', 'player': 'Heung-Min Son', 'rank': 81, 'team': 'Tottenham Hotspur'},
    {'nationality': 'Germany', 'player': 'Nick Woltemade', 'rank': 82, 'team': 'Stuttgart'},
    {'nationality': 'Cameroon', 'player': 'André-Frank Zambo Anguissa', 'rank': 83, 'team': 'Napoli'},
    {'nationality': 'Portugal', 'player': 'Rúben Santos Gato Alves Dias', 'rank': 84, 'team': 'Manchester City'},
    {'nationality': 'England', 'player': 'Tino Livramento', 'rank': 85, 'team': 'Newcastle United'},
    {'nationality': 'England', 'player': 'Morgan Rogers', 'rank': 86, 'team': 'Aston Villa'},
    {'nationality': 'Colombia', 'player': 'James David Rodríguez Rubio', 'rank': 87, 'team': 'Rayo Vallecano'},
    {'nationality': 'Hungary', 'player': 'Milos Kerkez', 'rank': 88, 'team': 'Bournemouth'},
    {'nationality': 'Turkey', 'player': 'Kenan Yildiz', 'rank': 89, 'team': 'Juventus'},
    {'nationality': 'Serbia', 'player': 'Mile Svilar', 'rank': 90, 'team': 'Roma'},
    {'nationality': 'Netherlands', 'player': 'Tijjani Reijnders', 'rank': 91, 'team': 'AC Milan'},
    {'nationality': 'Switzerland', 'player': 'Granit Xhaka', 'rank': 92, 'team': 'Bayer Leverkusen'},
    {'nationality': 'Spain', 'player': 'Alejandro Grimaldo García', 'rank': 93, 'team': 'Bayer Leverkusen'},
    {'nationality': 'Germany', 'player': 'Leroy Sané', 'rank': 94, 'team': 'Bayern Munich'},
    {'nationality': 'Belgium', 'player': 'Loïs Openda', 'rank': 95, 'team': 'RB Leipzig'},
    {'nationality': 'England', 'player': 'Ollie Watkins', 'rank': 96, 'team': 'Aston Villa'},
    {'nationality': 'Canada', 'player': 'Jonathan David', 'rank': 97, 'team': 'Lille'},
    {'nationality': 'Brazil', 'player': 'Lucas Paquetá', 'rank': 98, 'team': 'West Ham United'},
    {'nationality': 'Argentina', 'player': 'Damián Emiliano Martínez', 'rank': 99, 'team': 'Aston Villa'},
    {'nationality': 'Ghana', 'player': 'Mohammed Kudus', 'rank': 100, 'team': 'West Ham United'}
]