rosters_2026 = {
    'Spain': {
        'Unai Simón': {'club': 'Athletic Club', 'age': 28},
        'David Raya': {'club': 'Arsenal', 'age': 30},
        'Dani Carvajal': {'club': 'Real Madrid', 'age': 34},
        'Aymeric Laporte': {'club': 'Al-Nassr', 'age': 31},
        'Robin Le Normand': {'club': 'Atlético Madrid', 'age': 29},
        'Dani Vivian': {'club': 'Athletic Club', 'age': 26},
        'Marc Cucurella Saseta': {'club': 'Chelsea', 'age': 27},
        'Alejandro Grimaldo García': {'club': 'Bayer Leverkusen', 'age': 30},
        'Rodri': {'club': 'Manchester City', 'age': 29},
        'Fabián Ruiz Peña': {'club': 'Paris Saint-Germain', 'age': 29},
        'Pedri': {'club': 'Barcelona', 'age': 23},
        'Gavi': {'club': 'Barcelona', 'age': 21},
        'Daniel Olmo': {'club': 'Barcelona', 'age': 27},
        'Mikel Merino': {'club': 'Arsenal', 'age': 29},
        'Martín Zubimendi': {'club': 'Real Sociedad', 'age': 27},
        'Álvaro Morata': {'club': 'AC Milan', 'age': 33},
        'Neco Williams': {'club': 'Athletic Club', 'age': 23},
        'Lamine Yamal': {'club': 'Barcelona', 'age': 18},
        'Ferran Torres': {'club': 'Barcelona', 'age': 26},
        'Mikel Oyarzabal Ugarte': {'club': 'Real Sociedad', 'age': 28},
        'Joselu': {'club': 'Al-Gharafa', 'age': 35},
        'Ayoze Pérez': {'club': 'Villarreal', 'age': 32},
        'Bryan Gil': {'club': 'Girona', 'age': 25},
        'Pau Cubarsí': {'club': 'Barcelona', 'age': 19}
    },
    
    'Argentina': {
        'Emiliano Martínez': {'club': 'Aston Villa', 'age': 33},
        'Cristian Romero': {'club': 'Tottenham Hotspur', 'age': 27},
        'Lisandro Martínez': {'club': 'Manchester United', 'age': 28},
        'Nicolás Hernán Otamendi': {'club': 'Benfica', 'age': 38},
        'Gonzalo Montiel': {'club': 'Sevilla', 'age': 29},
        'Nahuel Molina': {'club': 'Atlético Madrid', 'age': 27},
        'Marcos Acuña': {'club': 'River Plate', 'age': 34},
        'Nicolás Tagliafico': {'club': 'Lyon', 'age': 33},
        'Rodrigo Javier De Paul': {'club': 'Atlético Madrid', 'age': 31},
        'Leandro Daniel Paredes': {'club': 'Roma', 'age': 31},
        'Alexis Mac Allister': {'club': 'Liverpool', 'age': 27},
        'Enzo Fernandez': {'club': 'Chelsea', 'age': 25},
        'Giovani Lo Celso': {'club': 'Real Betis', 'age': 29},
        'Exequiel Palacios': {'club': 'Bayer Leverkusen', 'age': 27},
        'Lionel Messi': {'club': 'Inter Miami', 'age': 38},
        'Julián Álvarez': {'club': 'Atlético Madrid', 'age': 26},
        'Lautaro Martínez': {'club': 'Inter Milan', 'age': 28},
        'Nicolás González': {'club': 'Juventus', 'age': 27},
        'Paulo Dybala': {'club': 'Roma', 'age': 32},
        'Alejandro Garnacho Ferreyra': {'club': 'Manchester United', 'age': 21},
        'Thiago Almada': {'club': 'Botafogo', 'age': 24},
        'Valentín Carboni': {'club': 'Marseille', 'age': 21},
        'Franco Mastantuono': {'club': 'Real Madrid', 'age': 18},
        'Nico Paz': {'club': 'Como (Real Madrid loan)', 'age': 21}
    },
    
    'England': {
        'Jordan Pickford': {'club': 'Everton', 'age': 32},
        'Aaron Ramsdale': {'club': 'Southampton', 'age': 27},
        'Kyle Walker': {'club': 'Manchester City', 'age': 35},
        'John Stones': {'club': 'Manchester City', 'age': 31},
        'Harry Maguire': {'club': 'Manchester United', 'age': 33},
        'Marc Guehi': {'club': 'Crystal Palace', 'age': 25},
        'Luke Shaw': {'club': 'Manchester United', 'age': 30},
        'Trent Alexander-Arnold': {'club': 'Real Madrid', 'age': 27},
        'Declan Rice': {'club': 'Arsenal', 'age': 27},
        'Jude Bellingham': {'club': 'Real Madrid', 'age': 22},
        'Phil Foden': {'club': 'Manchester City', 'age': 25},
        'Bukayo Saka': {'club': 'Arsenal', 'age': 24},
        'James Maddison': {'club': 'Tottenham Hotspur', 'age': 29},
        'Kobbie Mainoo': {'club': 'Manchester United', 'age': 20},
        'Conor Gallagher': {'club': 'Atlético Madrid', 'age': 26},
        'Cole Palmer': {'club': 'Chelsea', 'age': 23},
        'Harry Kane': {'club': 'Bayern Munich', 'age': 32},
        'Marcus Rashford': {'club': 'Manchester United', 'age': 28},
        'Anthony Gordon': {'club': 'Newcastle United', 'age': 25},
        'Ollie Watkins': {'club': 'Aston Villa', 'age': 30},
        'Ivan Toney': {'club': 'Al-Ahli', 'age': 29},
        'Jarrod Bowen': {'club': 'West Ham United', 'age': 29},
        'Jack Grealish': {'club': 'Manchester City', 'age': 30}
    },
    
    'France': {
        'Mike Maignan': {'club': 'AC Milan', 'age': 30},
        'Alphonse Areola': {'club': 'West Ham United', 'age': 33},
        'Jules Koundé': {'club': 'Barcelona', 'age': 27},
        'Dayot Upamecano': {'club': 'Bayern Munich', 'age': 27},
        'Ibrahima Konaté': {'club': 'Liverpool', 'age': 26},
        'William Saliba': {'club': 'Arsenal', 'age': 24},
        'Theo Hernández': {'club': 'AC Milan', 'age': 28},
        'Benjamin Pavard': {'club': 'Inter Milan', 'age': 29},
        'Aurélien Djani Tchouaméni': {'club': 'Real Madrid', 'age': 26},
        'Eduardo Camavinga': {'club': 'Real Madrid', 'age': 23},
        'N\'Golo Kanté': {'club': 'Al-Ittihad', 'age': 34},
        'Adrien Rabiot': {'club': 'Marseille', 'age': 30},
        'Antoine Griezmann': {'club': 'Atlético Madrid', 'age': 34},
        'Ousmane Dembélé': {'club': 'Paris Saint-Germain', 'age': 28},
        'Kylian Mbappé': {'club': 'Real Madrid', 'age': 27},
        'Randal Kolo Muani': {'club': 'Paris Saint-Germain', 'age': 27},
        'Marcus Thuram': {'club': 'Inter Milan', 'age': 28},
        'Kingsley Coman': {'club': 'Bayern Munich', 'age': 29},
        'Bradley Barcola': {'club': 'Paris Saint-Germain', 'age': 23},
        'Christopher Nkunku': {'club': 'Chelsea', 'age': 28},
        'Youssouf Fofana': {'club': 'AC Milan', 'age': 27},
        'Warren Zaïre-Emery': {'club': 'Paris Saint-Germain', 'age': 20}
    },
    
    'Germany': {
        'Marc-André ter Stegen': {'club': 'Barcelona', 'age': 33},
        'Oliver Baumann': {'club': 'TSG Hoffenheim', 'age': 35},
        'Antonio Rüdiger': {'club': 'Real Madrid', 'age': 33},
        'Nico Schlotterbeck': {'club': 'Borussia Dortmund', 'age': 26},
        'Jonathan Tah': {'club': 'Bayer Leverkusen', 'age': 30},
        'David Raum': {'club': 'RB Leipzig', 'age': 27},
        'Joshua Kimmich': {'club': 'Bayern Munich', 'age': 31},
        'Jamal Musiala': {'club': 'Bayern Munich', 'age': 23},
        'Florian Wirtz': {'club': 'Bayer Leverkusen', 'age': 22},
        'Leon Goretzka': {'club': 'Bayern Munich', 'age': 31},
        'Kai Havertz': {'club': 'Arsenal', 'age': 26},
        'Leroy Sané': {'club': 'Bayern Munich', 'age': 30},
        'Serge Gnabry': {'club': 'Bayern Munich', 'age': 30},
        'Niclas Füllkrug': {'club': 'West Ham United', 'age': 33},
        'Karim Adeyemi': {'club': 'Borussia Dortmund', 'age': 24},
        'Pascal Groß': {'club': 'Borussia Dortmund', 'age': 34},
        'Robert Andrich': {'club': 'Bayer Leverkusen', 'age': 31},
        'Maximilian Mittelstädt': {'club': 'VfB Stuttgart', 'age': 28},
        'Aleksandar Pavlović': {'club': 'Bayern Munich', 'age': 21},
        'Chris Führich': {'club': 'VfB Stuttgart', 'age': 28},
        'Emre Can': {'club': 'Borussia Dortmund', 'age': 32},
        'Julian Brandt': {'club': 'Borussia Dortmund', 'age': 29},
        'Lennart Karl': {'club': 'Bayern Munich', 'age': 18}
    },
    
    'Brazil': {
        'Alisson': {'club': 'Liverpool', 'age': 33},
        'Ederson': {'club': 'Manchester City', 'age': 32},
        'Danilo': {'club': 'Juventus', 'age': 34},
        'Marquinhos': {'club': 'Paris Saint-Germain', 'age': 31},
        'Éder Militão': {'club': 'Real Madrid', 'age': 28},
        'Gabriel Magalhães': {'club': 'Arsenal', 'age': 28},
        'Guilherme Arana': {'club': 'Atlético Mineiro', 'age': 28},
        'Renan Lodi': {'club': 'Al-Hilal', 'age': 27},
        'Casemiro': {'club': 'Manchester United', 'age': 34},
        'Douglas Luiz': {'club': 'Juventus', 'age': 27},
        'Bruno Guimarães': {'club': 'Newcastle United', 'age': 28},
        'Lucas Paquetá': {'club': 'West Ham United', 'age': 28},
        'Neymar': {'club': 'Al-Hilal', 'age': 34},
        'Vinícius Jr.': {'club': 'Real Madrid', 'age': 25},
        'Rodrygo': {'club': 'Real Madrid', 'age': 25},
        'Raphinha': {'club': 'Barcelona', 'age': 29},
        'Luiz Henrique': {'club': 'Botafogo', 'age': 25},
        'Gabriel Jesus': {'club': 'Arsenal', 'age': 28},
        'Richarlison': {'club': 'Tottenham Hotspur', 'age': 28},
        'Gabriel Martinelli': {'club': 'Arsenal', 'age': 24},
        'Endrick': {'club': 'Real Madrid', 'age': 19},
        'Savinho': {'club': 'Manchester City', 'age': 21},
        'Estêvão': {'club': 'Chelsea', 'age': 18},
        'Andrey Santos': {'club': 'Strasbourg (Chelsea loan)', 'age': 21}
    },
    
    'Netherlands': {
        'Bart Verbruggen': {'club': 'Brighton', 'age': 23},
        'Virgil van Dijk': {'club': 'Liverpool', 'age': 34},
        'Matthijs de Ligt': {'club': 'Manchester United', 'age': 26},
        'Nathan Aké': {'club': 'Manchester City', 'age': 31},
        'Denzel Dumfries': {'club': 'Inter Milan', 'age': 29},
        'Jeremie Frimpong': {'club': 'Bayer Leverkusen', 'age': 25},
        'Frenkie de Jong': {'club': 'Barcelona', 'age': 28},
        'Tijjani Reijnders': {'club': 'AC Milan', 'age': 27},
        'Ryan Gravenberch': {'club': 'Liverpool', 'age': 23},
        'Xavi Simons': {'club': 'RB Leipzig', 'age': 22},
        'Teun Koopmeiners': {'club': 'Juventus', 'age': 28},
        'Memphis Depay': {'club': 'Corinthians', 'age': 32},
        'Cody Gakpo': {'club': 'Liverpool', 'age': 26},
        'Donyell Malen': {'club': 'Borussia Dortmund', 'age': 27},
        'Steven Bergwijn': {'club': 'Al-Ittihad', 'age': 28},
        'Wout Weghorst': {'club': 'Ajax', 'age': 33},
        'Brian Brobbey': {'club': 'Ajax', 'age': 24},
        'Joey Veerman': {'club': 'PSV Eindhoven', 'age': 27},
        'Mats Wieffer': {'club': 'Brighton', 'age': 26},
        'Jurriën Timber': {'club': 'Arsenal', 'age': 24},
        'Ian Maatsen': {'club': 'Aston Villa', 'age': 23}
    },
    
    'Portugal': {
        'Diogo Costa': {'club': 'Porto', 'age': 26},
        'Rui Patrício': {'club': 'Atalanta', 'age': 38},
        'Rúben Dias': {'club': 'Manchester City', 'age': 28},
        'Gonçalo Inácio': {'club': 'Sporting CP', 'age': 24},
        'Danilo Pereira': {'club': 'Al-Ittihad', 'age': 34},
        'João Cancelo': {'club': 'Al-Hilal', 'age': 31},
        'Nuno Mendes': {'club': 'Paris Saint-Germain', 'age': 23},
        'João Palhinha': {'club': 'Bayern Munich', 'age': 30},
        'Rúben Neves': {'club': 'Al-Hilal', 'age': 28},
        'Bernardo Silva': {'club': 'Manchester City', 'age': 31},
        'Bruno Fernandes': {'club': 'Manchester United', 'age': 31},
        'Vitinha': {'club': 'Paris Saint-Germain', 'age': 26},
        'João Félix': {'club': 'Chelsea', 'age': 26},
        'Rafael Leão': {'club': 'AC Milan', 'age': 26},
        'Cristiano Ronaldo': {'club': 'Al-Nassr', 'age': 41},
        'Gonçalo Ramos': {'club': 'Paris Saint-Germain', 'age': 24},
        'Diogo Jota': {'club': 'Liverpool', 'age': 29},
        'Pedro Neto': {'club': 'Chelsea', 'age': 25},
        'João Neves': {'club': 'Paris Saint-Germain', 'age': 21},
        'António Silva': {'club': 'Benfica', 'age': 22}
    },
    
    'United States': {
        'Matt Turner': {'club': 'Crystal Palace', 'age': 31},
        'Patrick Schulte': {'club': 'Columbus Crew', 'age': 25},
        'Sergiño Dest': {'club': 'PSV Eindhoven', 'age': 25},
        'Antonee Robinson': {'club': 'Fulham', 'age': 28},
        'Chris Richards': {'club': 'Crystal Palace', 'age': 25},
        'Cameron Carter-Vickers': {'club': 'Celtic', 'age': 28},
        'Tim Ream': {'club': 'Charlotte FC', 'age': 38},
        'Joe Scally': {'club': 'Borussia Mgladbach', 'age': 23},
        'Tyler Adams': {'club': 'Bournemouth', 'age': 27},
        'Weston McKennie': {'club': 'Juventus', 'age': 27},
        'Yunus Musah': {'club': 'AC Milan', 'age': 23},
        'Gio Reyna': {'club': 'Borussia Dortmund', 'age': 23},
        'Malik Tillman': {'club': 'PSV Eindhoven', 'age': 23},
        'Christian Pulisic': {'club': 'AC Milan', 'age': 27},
        'Timothy Weah': {'club': 'Juventus', 'age': 26},
        'Folarin Balogun': {'club': 'Monaco', 'age': 24},
        'Ricardo Pepi': {'club': 'PSV Eindhoven', 'age': 23},
        'Haji Wright': {'club': 'Coventry City', 'age': 27},
        'Josh Sargent': {'club': 'Norwich City', 'age': 26},
        'Johnny Cardoso': {'club': 'Real Betis', 'age': 24},
        'Tanner Tessmann': {'club': 'Lyon', 'age': 24}
    },

    'Mexico': {
        'Luis Malagón': {'club': 'Club América', 'age': 29},
        'Edson Álvarez': {'club': 'West Ham United', 'age': 28},
        'Santiago Tomás Giménez': {'club': 'AC Milan', 'age': 24},
        'Hirving Lozano': {'club': 'San Diego FC', 'age': 30},
        'Raúl Jiménez': {'club': 'Fulham', 'age': 34},
        'Gilberto Mora': {'club': 'Feyenoord', 'age': 17},
        'Johan Vásquez': {'club': 'Genoa', 'age': 27},
        'Jorge Sánchez': {'club': 'Cruz Azul', 'age': 28},
        'César Montes': {'club': 'Lokomotiv Moscow', 'age': 29}
    },

    'Uruguay': {
        'Sergio Rochet': {'club': 'Internacional', 'age': 32},
        'Federico Valverde': {'club': 'Real Madrid', 'age': 27}, 
        'Darwin Núñez': {'club': 'Al Hilal', 'age': 26},
        'Ronald Araújo': {'club': 'Barcelona', 'age': 27},
        'Manuel Ugarte': {'club': 'Manchester United', 'age': 24},
        'José María Giménez': {'club': 'Atlético Madrid', 'age': 31},
        'Mathías Olivera': {'club': 'Napoli', 'age': 28},
        'Facundo Pellistri': {'club': 'Panathinaikos', 'age': 24},
        'Nicolás de la Cruz': {'club': 'Flamengo', 'age': 28},
        'Nahitan Nández': {'club': 'Al-Qadsiah', 'age': 30},
        'Luciano Rodríguez': {'club': 'Bahia', 'age': 22},
        'Rodrigo Bentancur Colmán': {'club': 'Tottenham Hotspur', 'age': 28}
    },

    'Croatia': {
        'Dominik Livaković': {'club': 'Fenerbahçe', 'age': 31},
        'Joško Gvardiol': {'club': 'Manchester City', 'age': 24},
        'Josip Juranović': {'club': 'Union Berlin', 'age': 30},
        'Borna Sosa': {'club': 'Torino', 'age': 28},
        'Luka Modrić': {'club': 'AC Milan', 'age': 40},
        'Mateo Kovačić': {'club': 'Manchester City', 'age': 31},
        'Marcelo Brozović': {'club': 'Al-Nassr', 'age': 33},
        'Mario Pašalić': {'club': 'Atalanta', 'age': 31},
        'Luka Sučić': {'club': 'Real Sociedad', 'age': 23},
        'Lovro Majer': {'club': 'Wolfsburg', 'age': 28},
        'Ivan Perišić': {'club': 'PSV Eindhoven', 'age': 37},
        'Andrej Kramarić': {'club': 'TSG Hoffenheim', 'age': 34},
        'Bruno Petković': {'club': 'Dinamo Zagreb', 'age': 31},
        'Josip Stanišić': {'club': 'Bayern Munich', 'age': 25},
        'Joško Šutalo': {'club': 'Ajax', 'age': 26}
    },

    'Belgium': {
        'Thibaut Courtois': {'club': 'Real Madrid', 'age': 33}, 
        'Kevin De Bruyne': {'club': 'Napoli', 'age': 34}, 
        'Jérémy Doku': {'club': 'Manchester City', 'age': 23},
        'Amadou Onana': {'club': 'Aston Villa', 'age': 24},
        'Loïs Openda': {'club': 'Juventus', 'age': 26}, 
        'Charles De Ketelaere': {'club': 'Atalanta', 'age': 24},
        'Youri Tielemans': {'club': 'Aston Villa', 'age': 28}, 
        'Arthur Theate': {'club': 'Eintracht Frankfurt', 'age': 25},
        'Maxim De Cuyper': {'club': 'Club Brugge', 'age': 25},
        'Leandro Trossard': {'club': 'Arsenal', 'age': 31},
        'Zeno Debast': {'club': 'Sporting CP', 'age': 22}
    },

    'Japan': {
        'Zion Suzuki': {'club': 'Parma', 'age': 23},
        'Wataru Endo': {'club': 'Liverpool', 'age': 33},
        'Takefusa Kubo': {'club': 'Real Sociedad', 'age': 24},
        'Kaoru Mitoma': {'club': 'Brighton', 'age': 28},
        'Ko Itakura': {'club': 'Borussia Mgladbach', 'age': 29},
        'Hiroki Ito': {'club': 'Bayern Munich', 'age': 26},
        'Ritsu Doan': {'club': 'SC Freiburg', 'age': 27},
        'Ayase Ueda': {'club': 'Feyenoord', 'age': 27},
        'Takehiro Tomiyasu': {'club': 'Arsenal', 'age': 27},
        'Daichi Kamada': {'club': 'Crystal Palace', 'age': 29}
    },

    'Switzerland': {
        'Gregor Kobel': {'club': 'Borussia Dortmund', 'age': 28}, 
        'Yann Sommer': {'club': 'Inter Milan', 'age': 37}, 
        'Manuel Akanji': {'club': 'Inter Milan', 'age': 30},
        'Granit Xhaka': {'club': 'Sunderland', 'age': 33}, 
        'Denis Zakaria': {'club': 'Monaco', 'age': 29}, 
        'Remo Freuler': {'club': 'Bologna', 'age': 33},
        'Dan Ndoye': {'club': 'Bologna', 'age': 25}, 
        'Ruben Vargas': {'club': 'Sevilla', 'age': 27}, 
        'Zeki Amdouni': {'club': 'Benfica', 'age': 25}
    },

    'Ecuador': {
        'Hernán Galíndez': {'club': 'Huracán', 'age': 38}, 
        'Piero Hincapié': {'club': 'Arsenal', 'age': 24}, 
        'Willian Pacho': {'club': 'Paris Saint-Germain', 'age': 24},
        'Pervis Estupiñán': {'club': 'Brighton', 'age': 28}, 
        'Moisés Caicedo': {'club': 'Chelsea', 'age': 24}, 
        'Kendry Páez': {'club': 'River Plate (Chelsea loan)', 'age': 18},
        'Enner Valencia': {'club': 'Pachuca', 'age': 36}, 
        'Gonzalo Plata': {'club': 'Flamengo', 'age': 25}, 
        'Jeremy Sarmiento': {'club': 'Brighton', 'age': 23},
        'Joel Ordóñez': {'club': 'Club Brugge', 'age': 21}
    },

    'Turkey': {
        'Altay Bayındır': {'club': 'Manchester United', 'age': 27}, 
        'Merih Demiral': {'club': 'Al-Ahli', 'age': 28}, 
        'Ferdi Kadıoğlu': {'club': 'Brighton', 'age': 26},
        'Hakan Çalhanoğlu': {'club': 'Inter Milan', 'age': 32}, 
        'Arda Güler': {'club': 'Real Madrid', 'age': 21}, 
        'Kenan Yıldız': {'club': 'Juventus', 'age': 20},
        'Can Uzun': {'club': 'Eintracht Frankfurt', 'age': 20}, 
        'Kerem Aktürkoğlu': {'club': 'Benfica', 'age': 27}, 
        'Barış Alper Yılmaz': {'club': 'Galatasaray', 'age': 25}
    },

    'Senegal': {
        'Édouard Mendy': {'club': 'Al-Ahli', 'age': 34}, 
        'Kalidou Koulibaly': {'club': 'Al-Hilal', 'age': 34}, 
        'Pape Matar Sarr': {'club': 'Tottenham Hotspur', 'age': 23},
        'Nicolas Jackson': {'club': 'Chelsea', 'age': 24}, 
        'Sadio Mané': {'club': 'Al-Nassr', 'age': 33}, 
        'Ismaïla Sarr': {'club': 'Crystal Palace', 'age': 28},
        'Idrissa Gueye': {'club': 'Everton', 'age': 36}, 
        'Lamine Camara': {'club': 'Monaco', 'age': 22}
    },

    'Canada': {
        'Maxime Crépeau': {'club': 'Portland Timbers', 'age': 31},
        'Alphonso Davies': {'club': 'Bayern Munich', 'age': 25},
        'Moïse Bombito': {'club': 'Nice', 'age': 25},
        'Ismaël Koné': {'club': 'Marseille', 'age': 23},
        'Stephen Eustáquio': {'club': 'LAFC', 'age': 29},
        'Jonathan David': {'club': 'Juventus', 'age': 26},
        'Jacob Shaffelburg': {'club': 'LAFC', 'age': 26},
        'Tajon Buchanan': {'club': 'Villarreal', 'age': 27}
    },

    'Nigeria': {
        'Stanley Nwabali': {'club': 'Chippa United', 'age': 29}, 
        'Calvin Bassey': {'club': 'Fulham', 'age': 26}, 
        'William Troost-Ekong': {'club': 'Al-Kholood', 'age': 32},
        'Wilfred Ndidi': {'club': 'Beşiktaş', 'age': 29}, 
        'Alex Iwobi': {'club': 'Fulham', 'age': 29}, 
        'Ademola Lookman': {'club': 'Atalanta', 'age': 28},
        'Victor James Osimhen': {'club': 'Galatasaray', 'age': 27}, 
        'Victor Okoh Boniface': {'club': 'Bayer Leverkusen', 'age': 25}, 
        'Samuel Chukwueze': {'club': 'Fulham', 'age': 26}
    },

    'Serbia': {
        'Djordje Petrović': {'club': 'Bournemouth', 'age': 26},
        'Nikola Milenković': {'club': 'Nottingham Forest', 'age': 28}, 
        'Strahinja Pavlović': {'club': 'AC Milan', 'age': 24},
        'Dušan Tadić': {'club': 'Fenerbahçe', 'age': 37}, 
        'Lazar Samardžić': {'club': 'Atalanta', 'age': 24}, 
        'Aleksandar Mitrović': {'club': 'Al-Hilal', 'age': 31},
        'Dušan Vlahović': {'club': 'Juventus', 'age': 26}, 
        'Filip Kostić': {'club': 'Fenerbahçe', 'age': 33}
    },

    'Austria': {
        'Patrick Pentz': {'club': 'Brøndby', 'age': 29}, 
        'David Alaba': {'club': 'Real Madrid', 'age': 33}, 
        'Kevin Danso': {'club': 'Tottenham Hotspur', 'age': 27},
        'Konrad Laimer': {'club': 'Bayern Munich', 'age': 28}, 
        'Marcel Sabitzer': {'club': 'Borussia Dortmund', 'age': 31}, 
        'Christoph Baumgartner': {'club': 'RB Leipzig', 'age': 26},
        'Nicolas Seiwald': {'club': 'RB Leipzig', 'age': 24}, 
        'Marko Arnautović': {'club': 'Crvena Zvezda', 'age': 36}
    },

    'Poland': {
        'Kamil Grabara': {'club': 'Wolfsburg', 'age': 27}, 
        'Jakub Piotr Kiwior': {'club': 'Porto', 'age': 26}, 
        'Matty Cash': {'club': 'Aston Villa', 'age': 28},
        'Piotr Zieliński': {'club': 'Inter Milan', 'age': 31}, 
        'Sebastian Szymański': {'club': 'Fenerbahçe', 'age': 26}, 
        'Nicola Zalewski': {'club': 'Roma', 'age': 24},
        'Robert Lewandowski': {'club': 'Barcelona', 'age': 37}, 
        'Karol Świderski': {'club': 'Charlotte FC', 'age': 29}
    },

    'Ghana': {
        'Lawrence Ati-Zigi': {'club': 'St. Gallen', 'age': 29}, 
        'Mohamed Salisu': {'club': 'Monaco', 'age': 26}, 
        'Tariq Lamptey': {'club': 'Brighton', 'age': 25},
        'Thomas Teye Partey': {'club': 'Arsenal', 'age': 32}, 
        'Mohammed Kudus': {'club': 'Tottenham', 'age': 25}, 
        'Antoine Semenyo': {'club': 'Bournemouth', 'age': 26},
        'Iñaki Williams': {'club': 'Athletic Club', 'age': 31}, 
        'Jordan Ayew': {'club': 'Leicester City', 'age': 34}
    },

    'Colombia': {
        'David Ospina': {'club': 'Atlético Nacional', 'age': 37},
        'Camilo Vargas': {'club': 'Atlas', 'age': 36},
        'Daniel Muñoz': {'club': 'Crystal Palace', 'age': 29},
        'Davinson Sánchez Mina': {'club': 'Galatasaray', 'age': 29},
        'Jhon Lucumí': {'club': 'Bologna', 'age': 27},
        'Carlos Cuesta': {'club': 'Vasco da Gama', 'age': 26},
        'Johan Mojica': {'club': 'Mallorca', 'age': 33},
        'Richard Ríos': {'club': 'Benfica', 'age': 25},
        'Jefferson Lerma': {'club': 'Crystal Palace', 'age': 31},
        'James Rodríguez': {'club': 'Minnesota United', 'age': 34},
        'Jhon Arias': {'club': 'Wolverhampton Wanderers', 'age': 28},
        'Luis Díaz': {'club': 'Bayern Munich', 'age': 29},
        'Jhon Durán': {'club': 'Aston Villa', 'age': 22},
        'Luis Sinisterra': {'club': 'Bournemouth', 'age': 26},
        'Yaser Asprilla': {'club': 'Girona', 'age': 22}
    },

    'Italy': {
        'Gianluigi Donnarumma': {'club': 'Manchester City', 'age': 27},
        'Guglielmo Vicario': {'club': 'Arsenal', 'age': 29},
        'Alessandro Bastoni': {'club': 'Inter Milan', 'age': 26},
        'Riccardo Calafiori': {'club': 'Arsenal', 'age': 23},
        'Alessandro Buongiorno': {'club': 'Napoli', 'age': 26},
        'Federico Dimarco': {'club': 'Inter Milan', 'age': 28},
        'Andrea Cambiaso': {'club': 'Juventus', 'age': 26},
        'Sandro Tonali': {'club': 'Newcastle United', 'age': 25},
        'Nicolò Barella': {'club': 'Inter Milan', 'age': 29},
        'Davide Frattesi': {'club': 'Inter Milan', 'age': 26},
        'Samuele Ricci': {'club': 'Torino', 'age': 24},
        'Mateo Retegui': {'club': 'Atalanta', 'age': 26},
        'Giacomo Raspadori': {'club': 'Napoli', 'age': 26},
        'Pio Esposito': {'club': 'Spezia (Inter loan)', 'age': 20},
        'Daniel Maldini': {'club': 'Monza', 'age': 24}
    }


}

MANAGER_TENURE = {
    'France': {'manager': 'Didier Deschamps', 'start_year': 2012},
    'Croatia': {'manager': 'Zlatko Dalić', 'start_year': 2017},
    'Argentina': {'manager': 'Lionel Scaloni', 'start_year': 2018},
    'Japan': {'manager': 'Hajime Moriyasu', 'start_year': 2018},
    'Serbia': {'manager': 'Dragan Stojković', 'start_year': 2021},
    'Spain': {'manager': 'Luis de la Fuente', 'start_year': 2022},
    'Morocco': {'manager': 'Walid Regragui', 'start_year': 2022},
    'Colombia': {'manager': 'Néstor Lorenzo', 'start_year': 2022},
    'Austria': {'manager': 'Ralf Rangnick', 'start_year': 2022},
    'Germany': {'manager': 'Julian Nagelsmann', 'start_year': 2023},
    'Portugal': {'manager': 'Roberto Martínez', 'start_year': 2023},
    'Netherlands': {'manager': 'Ronald Koeman', 'start_year': 2023},
    'Uruguay': {'manager': 'Marcelo Bielsa', 'start_year': 2023},
    'Turkey': {'manager': 'Vincenzo Montella', 'start_year': 2023},
    'USA': {'manager': 'Mauricio Pochettino', 'start_year': 2024},
    'Canada': {'manager': 'Jesse Marsch', 'start_year': 2024},
    'Mexico': {'manager': 'Javier Aguirre', 'start_year': 2024},
    'Denmark': {'manager': 'Brian Riemer', 'start_year': 2024},
    'South Korea': {'manager': 'Hong Myung-bo', 'start_year': 2024},
    'Ecuador': {'manager': 'Sebastián Beccacece', 'start_year': 2024},
    'Senegal': {'manager': 'Pape Thiaw', 'start_year': 2024},
    'Ghana': {'manager': 'Otto Addo', 'start_year': 2024},
    'Nigeria': {'manager': 'Éric Chelle', 'start_year': 2025},
    'Brazil': {'manager': 'Carlo Ancelotti', 'start_year': 2025},
    'England': {'manager': 'Thomas Tuchel', 'start_year': 2025},
    'Italy': {'manager': 'Gennaro Gattuso', 'start_year': 2025},
    'Belgium': {'manager': 'Rudi Garcia', 'start_year': 2025},
    'Poland': {'manager': 'Jan Urban', 'start_year': 2025}
}