rosters_2026 = {   'Spain': {   'Unai Simón Mendibil': {'club': 'Athletic Club', 'age': 28},
                 'David Raum': {'club': 'Arsenal', 'age': 30},
                 'Daniel Carvajal Ramos': {'club': 'Real Madrid', 'age': 34},
                 'Aymeric Laporte': {'club': 'Al-Nassr', 'age': 31},
                 'Robin Aime Robert Le Normand': {   'club': 'Atlético Madrid',
                                                     'age': 29},
                 'Daniel Vivian Moreno': {'club': 'Athletic Club', 'age': 26},
                 'Marc Cucurella Saseta': {'club': 'Chelsea', 'age': 27},
                 'Alejandro Grimaldo García': {   'club': 'Bayer Leverkusen',
                                                  'age': 30},
                 'Rodrigo Ely': {'club': 'Manchester City', 'age': 29},
                 'Fabián Ruiz Peña': {'club': 'Paris Saint-Germain', 'age': 29},
                 'Pedro González López': {'club': 'Barcelona', 'age': 23},
                 'Pablo Martín Páez Gavira': {'club': 'Barcelona', 'age': 21},
                 'Daniel Olmo Carvajal': {'club': 'Barcelona', 'age': 27},
                 'Mikel Merino Zazón': {'club': 'Arsenal', 'age': 29},
                 'Martín Zubimendi Ibáñez': {   'club': 'Real Sociedad',
                                                'age': 27},
                 'Álvaro Borja Morata Martín': {'club': 'AC Milan', 'age': 33},
                 'Neco Williams': {'club': 'Athletic Club', 'age': 23},
                 'Lamine Yamal Nasraoui Ebana': {   'club': 'Barcelona',
                                                    'age': 18},
                 'Ferrán Torres García': {'club': 'Barcelona', 'age': 26},
                 'Mikel Oyarzabal Ugarte': {'club': 'Real Sociedad', 'age': 28},
                 'José Luis Sanmartín Mato': {'club': 'Al-Gharafa', 'age': 35},
                 'Ayoze García Pérez': {'club': 'Villarreal', 'age': 32},
                 'Bryan Gil Salvatierra': {'club': 'Girona', 'age': 25},
                 'Pau Cubarsí Paredes ': {'club': 'Barcelona', 'age': 19}},
    'Argentina': {   'Damián Emiliano Martínez': {   'club': 'Aston Villa',
                                                     'age': 33},
                     'Cristian Gabriel Romero': {   'club': 'Tottenham Hotspur',
                                                    'age': 27},
                     'Lisandro Martínez': {   'club': 'Manchester United',
                                              'age': 28},
                     'Nicolás Hernán Otamendi': {'club': 'Benfica', 'age': 38},
                     'Gonzalo Ariel Montiel': {'club': 'Sevilla', 'age': 29},
                     'Nahuel Molina Lucero': {   'club': 'Atlético Madrid',
                                                 'age': 27},
                     'Marcos Javier Acuña': {'club': 'River Plate', 'age': 34},
                     'Nicolás Alejandro Tagliafico': {   'club': 'Lyon',
                                                         'age': 33},
                     'Rodrigo Javier De Paul': {   'club': 'Atlético Madrid',
                                                   'age': 31},
                     'Leandro Daniel Paredes': {'club': 'Roma', 'age': 31},
                     'Alexis Mac Allister': {'club': 'Liverpool', 'age': 27},
                     'Enzo Fernandez': {'club': 'Chelsea', 'age': 25},
                     'Giovani Lo Celso': {'club': 'Real Betis', 'age': 29},
                     'Exequiel Alejandro Palacios': {   'club': 'Bayer '
                                                                'Leverkusen',
                                                        'age': 27},
                     'Lionel Andrés Messi Cuccittini': {   'club': 'Inter '
                                                                   'Miami',
                                                           'age': 38},
                     'Julián Álvarez': {'club': 'Atlético Madrid', 'age': 26},
                     'Lautaro Javier Martínez': {   'club': 'Inter Milan',
                                                    'age': 28},
                     'Nicolás Iván González': {'club': 'Juventus', 'age': 27},
                     'Paulo Bruno Exequiel Dybala': {'club': 'Roma', 'age': 32},
                     'Alejandro Garnacho Ferreyra': {   'club': 'Manchester '
                                                                'United',
                                                        'age': 21},
                     'Thiago Ezequiel Almada': {'club': 'Botafogo', 'age': 24},
                     'Valentin Carboni': {'club': 'Marseille', 'age': 21},
                     'Franco Mastantuono': {'club': 'Real Madrid', 'age': 18},
                     'Nicolás Paz Martínez': {   'club': 'Como',
                                     'age': 21}},
    'England': {   'Jordan Pickford': {'club': 'Everton', 'age': 32},
                   'Aaron Ramsey': {'club': 'Southampton', 'age': 27},
                   'Kyle Walker': {'club': 'Manchester City', 'age': 35},
                   'John Stones': {'club': 'Manchester City', 'age': 31},
                   'Harry Maguire': {'club': 'Manchester United', 'age': 33},
                   'Marc Guehi': {'club': 'Crystal Palace', 'age': 25},
                   'Luke Shaw': {'club': 'Manchester United', 'age': 30},
                   'Trent Alexander-Arnold': {'club': 'Real Madrid', 'age': 27},
                   'Declan Rice': {'club': 'Arsenal', 'age': 27},
                   'Jude Bellingham': {'club': 'Real Madrid', 'age': 22},
                   'Philip Foden': {'club': 'Manchester City', 'age': 25},
                   'Bukayo Saka': {'club': 'Arsenal', 'age': 24},
                   'James Maddison': {'club': 'Tottenham Hotspur', 'age': 29},
                   'Kobbie Mainoo': {'club': 'Manchester United', 'age': 20},
                   'Conor Gallagher': {'club': 'Atlético Madrid', 'age': 26},
                   'Cole Palmer': {'club': 'Chelsea', 'age': 23},
                   'Harry Kane': {'club': 'Bayern Munich', 'age': 32},
                   'Marcus Rashford': {'club': 'Manchester United', 'age': 28},
                   'Anthony Gordon': {'club': 'Newcastle United', 'age': 25},
                   'Ollie Watkins': {'club': 'Aston Villa', 'age': 30},
                   'Ivan Toney': {'club': 'Al-Ahli', 'age': 29},
                   'Jarrod Bowen': {'club': 'West Ham United', 'age': 29},
                   'Jack Grealish': {'club': 'Manchester City', 'age': 30}},
    'France': {   'Mike Maignan': {'club': 'AC Milan', 'age': 30},
                  'Alphonse Areola': {'club': 'West Ham United', 'age': 33},
                  'Jules Koundé': {'club': 'Barcelona', 'age': 27},
                  'Dayotchanculle Upamecano': {'club': 'Bayern Munich', 'age': 27},
                  'Ibrahima Konaté': {'club': 'Liverpool', 'age': 26},
                  'William Saliba': {'club': 'Arsenal', 'age': 24},
                  'Theo Bernard François Hernández': {   'club': 'AC Milan',
                                                         'age': 28},
                  'Benjamin Pavard': {'club': 'Inter Milan', 'age': 29},
                  'Aurélien Djani Tchouaméni': {   'club': 'Real Madrid',
                                                   'age': 26},
                  'Eduardo Camavinga': {'club': 'Real Madrid', 'age': 23},
                  "N'Golo Kanté": {'club': 'Al-Ittihad', 'age': 34},
                  'Adrien Rabiot': {'club': 'Marseille', 'age': 30},
                  'Antoine Griezmann': {'club': 'Atlético Madrid', 'age': 34},
                  'Ousmane Dembélé': {'club': 'Paris Saint-Germain', 'age': 28},
                  'Kylian Mbappé Lottin': {'club': 'Real Madrid', 'age': 27},
                  'Randal Kolo Muani': {   'club': 'Paris Saint-Germain',
                                           'age': 27},
                  'Marcus Thuram': {'club': 'Inter Milan', 'age': 28},
                  'Kingsley Coman': {'club': 'Bayern Munich', 'age': 29},
                  'Bradley Barcola': {'club': 'Paris Saint-Germain', 'age': 23},
                  'Christopher Nkunku': {'club': 'Chelsea', 'age': 28},
                  'Youssouf Fofana': {'club': 'AC Milan', 'age': 27},
                  'Warren Zaire Emery': {   'club': 'Paris Saint-Germain',
                                            'age': 20}},
    'Germany': {   'Marc-André ter Stegen': {'club': 'Barcelona', 'age': 33},
                   'Oliver Baumann': {'club': 'TSG Hoffenheim', 'age': 35},
                   'Antonio Rüdiger': {'club': 'Real Madrid', 'age': 33},
                   'Nico Schlotterbeck': {   'club': 'Borussia Dortmund',
                                             'age': 26},
                   'Jonathan Tah': {'club': 'Bayer Leverkusen', 'age': 30},
                   'David Raum': {'club': 'RB Leipzig', 'age': 27},
                   'Joshua Kimmich': {'club': 'Bayern Munich', 'age': 31},
                   'Jamal Musiala': {'club': 'Bayern Munich', 'age': 23},
                   'Florian Wirtz': {'club': 'Bayer Leverkusen', 'age': 22},
                   'Leon Goretzka': {'club': 'Bayern Munich', 'age': 31},
                   'Kai Havertz': {'club': 'Arsenal', 'age': 26},
                   'Leroy Sané': {'club': 'Bayern Munich', 'age': 30},
                   'Serge Gnabry': {'club': 'Bayern Munich', 'age': 30},
                   'Niclas Füllkrug': {'club': 'West Ham United', 'age': 33},
                   'Karim-David Adeyemi': {   'club': 'Borussia Dortmund',
                                              'age': 24},
                   'Pascal Groß': {'club': 'Borussia Dortmund', 'age': 34},
                   'Robert Andrich': {'club': 'Bayer Leverkusen', 'age': 31},
                   'Maximilian Mittelstädt': {   'club': 'VfB Stuttgart',
                                                 'age': 28},
                   'Aleksandar Pavlović': {'club': 'Bayern Munich', 'age': 21},
                   'Chris Führich': {'club': 'VfB Stuttgart', 'age': 28},
                   'Emre Can': {'club': 'Borussia Dortmund', 'age': 32},
                   'Julian Brandt': {'club': 'Borussia Dortmund', 'age': 29},
                   'Karl Lennart Skoglund': {   'club': 'Bayern Munich',
                                                'age': 18}},
    'Brazil': {   'Alisson Ramsés Becker': {'club': 'Liverpool', 'age': 33},
                  'Ederson Santana de Moraes': {'club': 'Manchester City', 'age': 32},
                  'Danilo Luiz da Silva': {'club': 'Juventus', 'age': 34},
                  'Marcos Aoás Corrêa': {'club': 'Paris Saint-Germain', 'age': 31},
                  'Éder Gabriel Militão': {'club': 'Real Madrid', 'age': 28},
                  'Gabriel dos Santos Magalhães': {   'club': 'Arsenal',
                                                      'age': 28},
                  'Guilherme Antonio Arana Lopes': {   'club': 'Atlético '
                                                               'Mineiro',
                                                       'age': 28},
                  'Renan Augusto Lodi dos Santos': {   'club': 'Al-Hilal',
                                                       'age': 27},
                  'Carlos Henrique Casimiro': {'club': 'Manchester United', 'age': 34},
                  'Douglas Luiz Soares de Paulo': {   'club': 'Juventus',
                                                      'age': 27},
                  'Bruno Guimarães Rodriguez Moura': {   'club': 'Newcastle '
                                                                 'United',
                                                         'age': 28},
                  'Lucas Paquetá': {'club': 'West Ham United', 'age': 28},
                  'Neymar da Silva Santos Junior': {'club': 'Al-Hilal', 'age': 34},
                  'Vinícius José Paixão de Oliveira Júnior': {'club': 'Real Madrid', 'age': 25},
                  'Rodrygo Silva de Goes': {'club': 'Real Madrid', 'age': 25},
                  'Raphael Dias Belloli': {'club': 'Barcelona', 'age': 29},
                  'Luiz Henrique': {'club': 'Botafogo', 'age': 25},
                  'Gabriel Fernando de Jesus': {'club': 'Arsenal', 'age': 28},
                  'Richarlison de Andrade': {'club': 'Tottenham Hotspur', 'age': 28},
                  'Gabriel Teodoro Martinelli Silva': {   'club': 'Arsenal',
                                                          'age': 24},
                  'Endrick Felipe Moreira de Sousa': {'club': 'Real Madrid', 'age': 19},
                  'Sávio Moreira de Oliveira': {'club': 'Manchester City', 'age': 21},
                  'Estêvão Willian Almeida de Oliveira Gonçalves': {'club': 'Chelsea', 'age': 18},
                  'Andrey Santos': {   'club': 'Strasbourg',
                                       'age': 21}},
    'Netherlands': {   'Bart Verbruggen': {'club': 'Brighton', 'age': 23},
                       'Virgil van Dijk': {'club': 'Liverpool', 'age': 34},
                       'Matthijs de Ligt': {   'club': 'Manchester United',
                                               'age': 26},
                       'Nathan Aké': {'club': 'Manchester City', 'age': 31},
                       'Denzel Dumfries': {'club': 'Inter Milan', 'age': 29},
                       'Jeremie Frimpong': {   'club': 'Bayer Leverkusen',
                                               'age': 25},
                       'Frenkie de Jong': {'club': 'Barcelona', 'age': 28},
                       'Tijjani Reijnders': {'club': 'AC Milan', 'age': 27},
                       'Ryan Gravenberch': {'club': 'Liverpool', 'age': 23},
                       'Xavi Simons': {'club': 'RB Leipzig', 'age': 22},
                       'Teun Koopmeiners': {'club': 'Juventus', 'age': 28},
                       'Memphis Depay': {'club': 'Corinthians', 'age': 32},
                       'Cody Mathès Gakpo': {'club': 'Liverpool', 'age': 26},
                       'Donyell Malen': {   'club': 'Borussia Dortmund',
                                            'age': 27},
                       'Steven Bergwijn': {'club': 'Al-Ittihad', 'age': 28},
                       'Wout Weghorst': {'club': 'Ajax', 'age': 33},
                       'Brian Brobbey': {'club': 'Ajax', 'age': 24},
                       'Joey Veerman': {'club': 'PSV Eindhoven', 'age': 27},
                       'Mats Wieffer': {'club': 'Brighton', 'age': 26},
                       'Jurriën David Norman Timber': {   'club': 'Arsenal',
                                                          'age': 24},
                       'Ian Maatsen': {'club': 'Aston Villa', 'age': 23}},
    'Portugal': {   'Diogo Meireles Costa': {'club': 'Porto', 'age': 26},
                    'Rui Pedro dos Santos Patrício': {   'club': 'Atalanta',
                                                         'age': 38},
                    'Rúben Santos Gato Alves Dias': {   'club': 'Manchester '
                                                                'City',
                                                        'age': 28},
                    'Gonçalo Bernardo Inácio': {   'club': 'Sporting CP',
                                                   'age': 24},
                    'Danilo Luís Hélio Pereira': {   'club': 'Al-Ittihad',
                                                     'age': 34},
                    'João Pedro Cavaco Cancelo': {   'club': 'Al-Hilal',
                                                     'age': 31},
                    'Nuno Mendes': {'club': 'Paris Saint-Germain', 'age': 23},
                    'João Maria Lobo Alves Palhinha Gonçalves': {   'club': 'Bayern '
                                                                            'Munich',
                                                                    'age': 30},
                    'Rúben Diogo Da Silva Neves': {   'club': 'Al-Hilal',
                                                      'age': 28},
                    'Bernardo Fernandes da Silva Junior': {   'club': 'Manchester '
                                                                      'City',
                                                              'age': 31},
                    'Brandon Fernandes': {   'club': 'Manchester United',
                                             'age': 31},
                    'Vitor Machado Ferreira': {'club': 'Paris Saint-Germain', 'age': 26},
                    'João Félix Sequeira': {'club': 'Chelsea', 'age': 26},
                    'Rafael Alexandre Conceição Leão': {   'club': 'AC Milan',
                                                           'age': 26},
                    'Cristiano Ronaldo dos Santos Aveiro': {   'club': 'Al-Nassr',
                                                               'age': 41},
                    'Gonçalo Matias Ramos': {   'club': 'Paris Saint-Germain',
                                                'age': 24},
                    'Diogo José Teixeira da Silva': {'club': 'Liverpool', 'age': 29},
                    'Pedro Lomba Neto': {'club': 'Chelsea', 'age': 25},
                    'João Neves': {'club': 'Paris Saint-Germain', 'age': 21},
                    'António João Pereira Albuquerque Tavares Silva': {   'club': 'Benfica',
                                                                          'age': 22}},
    'United States': {   'Matt Turner': {'club': 'Crystal Palace', 'age': 31},
                         'Patrick Schulte': {   'club': 'Columbus Crew',
                                                'age': 25},
                         'Sergino Dest': {'club': 'PSV Eindhoven', 'age': 25},
                         'Antonee Robinson': {'club': 'Fulham', 'age': 28},
                         'Chris Richards': {   'club': 'Crystal Palace',
                                               'age': 25},
                         'Cameron Carter-Vickers': {   'club': 'Celtic',
                                                       'age': 28},
                         'Tim Ream': {'club': 'Charlotte FC', 'age': 38},
                         'Joseph Scally': {   'club': 'Borussia Mgladbach',
                                              'age': 23},
                         'Tyler Adams': {'club': 'Bournemouth', 'age': 27},
                         'Weston McKennie': {'club': 'Juventus', 'age': 27},
                         'Yunus Dimoara Musah': {'club': 'AC Milan', 'age': 23},
                         'Giovanni Reyna': {'club': 'Borussia Dortmund', 'age': 23},
                         'Malik Tillman': {'club': 'PSV Eindhoven', 'age': 23},
                         'Christian Pulisic': {'club': 'AC Milan', 'age': 27},
                         'Timothy Weah': {'club': 'Juventus', 'age': 26},
                         'Folarin Balogun': {'club': 'Monaco', 'age': 24},
                         'Ricardo Daniel Pepi': {   'club': 'PSV Eindhoven',
                                                    'age': 23},
                         'Haji Wright': {'club': 'Coventry City', 'age': 27},
                         'Joshua Sargent': {'club': 'Norwich City', 'age': 26},
                         'Johnny Cardoso': {'club': 'Real Betis', 'age': 24},
                         'Tanner Tessmann': {'club': 'Lyon', 'age': 24}},
    'Mexico': {   'Luis Ángel Malagón Velázquez': {'club': 'Club América', 'age': 29},
                  'Edson Omar Álvarez Velázquez': {   'club': 'West Ham United',
                                                      'age': 28},
                  'Santiago Tomás Giménez': {'club': 'AC Milan', 'age': 24},
                  'Hirving Rodrigo Lozano Bahena': {   'club': 'San Diego FC',
                                                       'age': 30},
                  'Raúl Alonso Jiménez Rodríguez': {   'club': 'Fulham',
                                                       'age': 34},
                  'Gilberto Moraes Junior': {'club': 'Feyenoord', 'age': 17},
                  'Johan Felipe Vásquez Ibarra': {'club': 'Genoa', 'age': 27},
                  'Jorge Eduardo Sánchez Ramos': {   'club': 'Cruz Azul',
                                                     'age': 28},
                  'César Jasib Montes Castro': {   'club': 'Lokomotiv Moscow',
                                                   'age': 29}},
    'Uruguay': {   'Sergio Rochet Álvarez': {   'club': 'Internacional',
                                                'age': 32},
                   'Federico Santiago Valverde Dipetta': {   'club': 'Real '
                                                                     'Madrid',
                                                             'age': 27},
                   'Darwin Gabriel Núñez Ribeiro': {   'club': 'Al Hilal',
                                                       'age': 26},
                   'Ronald Federico Araújo da Silva': {   'club': 'Barcelona',
                                                          'age': 27},
                   'Manuel Ugarte Ribeiro': {   'club': 'Manchester United',
                                                'age': 24},
                   'José María Giménez de Vargas': {   'club': 'Atlético '
                                                               'Madrid',
                                                       'age': 31},
                   'Mathías Olivera Miramontes': {'club': 'Napoli', 'age': 28},
                   'Facundo Pellistri Rebollo': {   'club': 'Panathinaikos',
                                                    'age': 24},
                   'Diego Nicolás De La Cruz Arcosa': {   'club': 'Flamengo',
                                                          'age': 28},
                   'Nahitan Michel Nández Acosta': {   'club': 'Al-Qadsiah',
                                                       'age': 30},
                   'Guido Rodríguez': {'club': 'Bahia', 'age': 22},
                   'Rodrigo Bentancur Colmán': {   'club': 'Tottenham Hotspur',
                                                   'age': 28}},
    'Croatia': {   'Dominik Livaković': {'club': 'Fenerbahçe', 'age': 31},
                   'Joško Gvardiol': {'club': 'Manchester City', 'age': 24},
                   'Josip Juranović': {'club': 'Union Berlin', 'age': 30},
                   'Borna Sosa': {'club': 'Torino', 'age': 28},
                   'Luka Modrić': {'club': 'AC Milan', 'age': 40},
                   'Mateo Kovačić': {'club': 'Manchester City', 'age': 31},
                   'Marcelo Brozović': {'club': 'Al-Nassr', 'age': 33},
                   'Mario Pašalić': {'club': 'Atalanta', 'age': 31},
                   'Luka Sučić': {'club': 'Real Sociedad', 'age': 23},
                   'Lovro Majer': {'club': 'Wolfsburg', 'age': 28},
                   'Ivan Perišić': {'club': 'PSV Eindhoven', 'age': 37},
                   'Andrej Kramarić': {'club': 'TSG Hoffenheim', 'age': 34},
                   'Bruno Petković': {'club': 'Dinamo Zagreb', 'age': 31},
                   'Josip Stanišić': {'club': 'Bayern Munich', 'age': 25},
                   'Joško Šutalo': {'club': 'Ajax', 'age': 26}},
    'Belgium': {   'Thibaut Courtois': {'club': 'Real Madrid', 'age': 33},
                   'Kevin De Bruyne': {'club': 'Napoli', 'age': 34},
                   'Jeremy Doku': {'club': 'Manchester City', 'age': 23},
                   'Amadou Onana': {'club': 'Aston Villa', 'age': 24},
                   'Ikoma Loïs Openda': {'club': 'Juventus', 'age': 26},
                   'Charles De Ketelaere': {'club': 'Atalanta', 'age': 24},
                   'Youri Tielemans': {'club': 'Aston Villa', 'age': 28},
                   'Arthur Theate': {'club': 'Eintracht Frankfurt', 'age': 25},
                   'Maxim De Cuyper': {'club': 'Club Brugge', 'age': 25},
                   'Leandro Trossard': {'club': 'Arsenal', 'age': 31},
                   'Zeno Debast': {'club': 'Sporting CP', 'age': 22}},
    'Japan': {   'Suzuki Zaion': {'club': 'Parma', 'age': 23},
                 'Wataru Endo': {'club': 'Liverpool', 'age': 33},
                 'Takefusa Kubo': {'club': 'Real Sociedad', 'age': 24},
                 'Kaoru Mitoma': {'club': 'Brighton', 'age': 28},
                 'Ko Itakura': {'club': 'Borussia Mgladbach', 'age': 29},
                 'Hiroki Ito': {'club': 'Bayern Munich', 'age': 26},
                 'Ritsu Doan': {'club': 'SC Freiburg', 'age': 27},
                 'Ayase Ueda': {'club': 'Feyenoord', 'age': 27},
                 'Takehiro Tomiyasu': {'club': 'Arsenal', 'age': 27},
                 'Daichi Kamada': {'club': 'Crystal Palace', 'age': 29}},
    'Switzerland': {   'Gregor Kobel': {'club': 'Borussia Dortmund', 'age': 28},
                       'Yann Sommer': {'club': 'Inter Milan', 'age': 37},
                       'Manuel Obafemi Akanji': {   'club': 'Inter Milan',
                                                    'age': 30},
                       'Granit Xhaka': {'club': 'Sunderland', 'age': 33},
                       'Denis Lemi Zakaria Lako Lado': {   'club': 'Monaco',
                                                           'age': 29},
                       'Remo Freuler': {'club': 'Bologna', 'age': 33},
                       'Dan Ndoye': {'club': 'Bologna', 'age': 25},
                       'Ruben Vargas': {'club': 'Sevilla', 'age': 27},
                       'Mohamed Zeki Amdouni': {'club': 'Benfica', 'age': 25}},
    'Ecuador': {   'Hernán Ismael Galíndez': {'club': 'Huracán', 'age': 38},
                   'Piero Martín Hincapié Reyna': {   'club': 'Arsenal',
                                                      'age': 24},
                   'Willian Joel Pacho Tenorio': {   'club': 'Paris '
                                                             'Saint-Germain',
                                                     'age': 24},
                   'Pervis Josué Estupiñán Tenorio': {   'club': 'Brighton',
                                                         'age': 28},
                   'Moisés Isaac Caicedo Corozo': {   'club': 'Chelsea',
                                                      'age': 24},
                   'Ray Kendry Páez Andrade': {   'club': 'River Plate ',
                                                  'age': 18},
                   'Enner Remberto Valencia Lastra': {   'club': 'Pachuca',
                                                         'age': 36},
                   'Gonzalo Jordy Plata Jiménez': {   'club': 'Flamengo',
                                                      'age': 25},
                   'Jeremy Leonel Sarmiento Morante': {   'club': 'Brighton',
                                                          'age': 23},
                   'Joel Ordóñez': {'club': 'Club Brugge', 'age': 21}},
    'Turkey': {   'Altay Bayındır': {'club': 'Manchester United', 'age': 27},
                  'Merih Demiral': {'club': 'Al-Ahli', 'age': 28},
                  'Ferdi Erenay Kadıoğlu': {'club': 'Brighton', 'age': 26},
                  'Hakan Çalhanoğlu': {'club': 'Inter Milan', 'age': 32},
                  'Arda Güler': {'club': 'Real Madrid', 'age': 21},
                  'Kenan Yildiz': {'club': 'Juventus', 'age': 20},
                  'Can Yilmaz Uzun': {'club': 'Eintracht Frankfurt', 'age': 20},
                  'Muhammed Kerem Aktürkoğlu': {'club': 'Benfica', 'age': 27},
                  'Barış Alper Yılmaz': {'club': 'Galatasaray', 'age': 25}},
    'Senegal': {   'Édouard Osoque Mendy': {'club': 'Al-Ahli', 'age': 34},
                   'Kalidou Koulibaly': {'club': 'Al-Hilal', 'age': 34},
                   'Pape Matar Sarr': {'club': 'Tottenham Hotspur', 'age': 23},
                   'Nicolas Jackson': {'club': 'Chelsea', 'age': 24},
                   'Sadio Mané': {'club': 'Al-Nassr', 'age': 33},
                   'Ismaïla Sarr': {'club': 'Crystal Palace', 'age': 28},
                   'Idrissa Gueye': {'club': 'Everton', 'age': 36},
                   'Lamine Camara': {'club': 'Monaco', 'age': 22}},
    'Canada': {   'Maxime Crépeau': {'club': 'Portland Timbers', 'age': 31},
                  'Alphonso Davies': {'club': 'Bayern Munich', 'age': 25},
                  'Moise Bombito': {'club': 'Nice', 'age': 25},
                  'Ismael Koné': {'club': 'Marseille', 'age': 23},
                  'Stephen Antunes Eustáquio': {'club': 'LAFC', 'age': 29},
                  'Jonathan David': {'club': 'Juventus', 'age': 26},
                  'Jacob Shaffelburg': {'club': 'LAFC', 'age': 26},
                  'Tajon Buchanan': {'club': 'Villarreal', 'age': 27}},
    'Nigeria': {   'Stanley Bobo Nwabali': {'club': 'Chippa United', 'age': 29},
                   'Calvin Bassey Ughelumba': {'club': 'Fulham', 'age': 26},
                   'William Troost-Ekong': {'club': 'Al-Kholood', 'age': 32},
                   'Onyinye Wilfred Ndidi': {'club': 'Beşiktaş', 'age': 29},
                   'Alex Iwobi': {'club': 'Fulham', 'age': 29},
                   'Ademola Lookman': {'club': 'Atalanta', 'age': 28},
                   'Victor James Osimhen': {'club': 'Galatasaray', 'age': 27},
                   'Victor Okoh Boniface': {   'club': 'Bayer Leverkusen',
                                               'age': 25},
                   'Samuel Chimerenka Chukwueze': {   'club': 'Fulham',
                                                      'age': 26}},
    'Serbia': {   'Đorđe Petrović': {'club': 'Bournemouth', 'age': 26},
                  'Nikola Milenković': {'club': 'Nottingham Forest', 'age': 28},
                  'Strahinja Pavlović': {'club': 'AC Milan', 'age': 24},
                  'Dušan Tadić': {'club': 'Fenerbahçe', 'age': 37},
                  'Lazar Samardžić': {'club': 'Atalanta', 'age': 24},
                  'Aleksandar Mitrović': {'club': 'Al-Hilal', 'age': 31},
                  'Dušan Vlahović': {'club': 'Juventus', 'age': 26},
                  'Filip Kostić': {'club': 'Fenerbahçe', 'age': 33}},
    'Austria': {   'Patrick Pentz': {'club': 'Brøndby', 'age': 29},
                   'David Olatukunbo Alaba': {'club': 'Real Madrid', 'age': 33},
                   'Kevin Danso': {'club': 'Tottenham Hotspur', 'age': 27},
                   'Konrad Laimer': {'club': 'Bayern Munich', 'age': 28},
                   'Marcel Sabitzer': {'club': 'Borussia Dortmund', 'age': 31},
                   'Christoph Baumgartner': {'club': 'RB Leipzig', 'age': 26},
                   'Nicolas Seiwald': {'club': 'RB Leipzig', 'age': 24},
                   'Marko Arnautović': {'club': 'Crvena Zvezda', 'age': 36}},
    'Poland': {   'Kamil Grabara': {'club': 'Wolfsburg', 'age': 27},
                  'Jakub Piotr Kiwior': {'club': 'Porto', 'age': 26},
                  'Matty Cash': {'club': 'Aston Villa', 'age': 28},
                  'Piotr Zieliński': {'club': 'Inter Milan', 'age': 31},
                  'Sebastian Szymański': {'club': 'Fenerbahçe', 'age': 26},
                  'Nicola Zalewski': {'club': 'Roma', 'age': 24},
                  'Robert Lewandowski': {'club': 'Barcelona', 'age': 37},
                  'Karol Świderski': {'club': 'Charlotte FC', 'age': 29}},
    'Ghana': {   'Lawrence Ati-Zigi': {'club': 'St. Gallen', 'age': 29},
                 'Mohamed Salisu': {'club': 'Monaco', 'age': 26},
                 'Tariq Lamptey': {'club': 'Brighton', 'age': 25},
                 'Thomas Teye Partey': {'club': 'Arsenal', 'age': 32},
                 'Mohammed Kudus': {'club': 'Tottenham', 'age': 25},
                 'Antoine Semenyo': {'club': 'Bournemouth', 'age': 26},
                 'Iñaki Williams Arthuer': {'club': 'Athletic Club', 'age': 31},
                 'Jordan Ayew': {'club': 'Leicester City', 'age': 34}},
    'Colombia': {   'David Ospina Ramírez': {   'club': 'Atlético Nacional',
                                                'age': 37},
                    'Camilo Andrés Vargas Gil': {'club': 'Atlas', 'age': 36},
                    'Daniel Muñoz Mejía': {'club': 'Crystal Palace', 'age': 29},
                    'Davinson Sánchez Mina': {'club': 'Galatasaray', 'age': 29},
                    'Jhon Janer Lucumí Bonilla': {'club': 'Bologna', 'age': 27},
                    'Carlos Eccehomo Cuesta Figueroa': {   'club': 'Vasco da '
                                                                   'Gama',
                                                           'age': 26},
                    'Johan Andrés Mojica Palacio': {   'club': 'Mallorca',
                                                       'age': 33},
                    'Richard Rios Montoya': {'club': 'Benfica', 'age': 25},
                    'Jefferson Andrés Lerma Solís': {   'club': 'Crystal '
                                                                'Palace',
                                                        'age': 31},
                    'James David Rodríguez Rubio': {   'club': 'Minnesota '
                                                               'United',
                                                       'age': 34},
                    'Jhon Adolfo Arias Andrade': {   'club': 'Wolverhampton '
                                                             'Wanderers',
                                                     'age': 28},
                    'Luis Alberto Suárez Díaz': {   'club': 'Bayern Munich',
                                                    'age': 29},
                    'Jhon Jáder Durán Palacio': {   'club': 'Aston Villa',
                                                    'age': 22},
                    'Luis Fernando Sinisterra Lucumí': {   'club': 'Bournemouth',
                                                           'age': 26},
                    'Yaser Esneider Asprilla Martínez': {   'club': 'Girona',
                                                            'age': 22}},
    'Italy': {   'Gianluigi Donnarumma': {'club': 'Manchester City', 'age': 27},
                 'Guglielmo Vicario': {'club': 'Arsenal', 'age': 29},
                 'Alessandro Bastoni': {'club': 'Inter Milan', 'age': 26},
                 'Riccardo Calafiori': {'club': 'Arsenal', 'age': 23},
                 'Alessandro Buongiorno': {'club': 'Napoli', 'age': 26},
                 'Federico Dimarco': {'club': 'Inter Milan', 'age': 28},
                 'Andrea Cambiaso': {'club': 'Juventus', 'age': 26},
                 'Sandro Tonali': {'club': 'Newcastle United', 'age': 25},
                 'Nicolò Barella': {'club': 'Inter Milan', 'age': 29},
                 'Davide Frattesi': {'club': 'Inter Milan', 'age': 26},
                 'Samuele Ricci': {'club': 'Torino', 'age': 24},
                 'Mateo Retegui': {'club': 'Atalanta', 'age': 26},
                 'Giacomo Raspadori': {'club': 'Napoli', 'age': 26},
                 'Francesco Pio Esposito': {'club': 'Spezia', 'age': 20},
                 'Daniel Maldini': {'club': 'Monza', 'age': 24}}}